# Makefile.in generated by automake 1.18.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2025 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
am__rm_f = rm -f $(am__rm_f_notfound)
am__rm_rf = rm -rf $(am__rm_f_notfound)
pkgdatadir = $(datadir)/tmux
pkgincludedir = $(includedir)/tmux
pkglibdir = $(libdir)/tmux
pkglibexecdir = $(libexecdir)/tmux
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = amd64-unknown-freebsd15.0
host_triplet = amd64-unknown-freebsd15.0
bin_PROGRAMS = tmux$(EXEEXT)

# Set flags for gcc.
am__append_1 = -std=gnu99
am__append_2 = -O2
#am__append_3 = -O0
am__append_4 = -g3 -ggdb -Wno-long-long \
	-Wall -W -Wformat=2 \
	-Wno-use-after-free \
	-Wmissing-prototypes \
	-Wstrict-prototypes \
	-Wmissing-declarations \
	-Wwrite-strings -Wshadow \
	-Wpointer-arith -Wsign-compare \
	-Wundef -Wbad-function-cast \
	-Winline -Wno-cast-align \
	-Wdeclaration-after-statement \
	-Wno-pointer-sign -Wno-attributes \
	-Wno-unused-result -Wno-format-y2k \
	-Wno-unknown-warning-option \
	-Wno-maybe-uninitialized
#am__append_5 = -Wno-deprecated-declarations -Wno-macro-redefined
am__append_6 = -DDEBUG
am__append_7 = -iquote.
#am__append_8 = -fsanitize=address
#am__append_9 = -fsanitize=address

# Set flags for Solaris.
#am__append_10 = -D_XPG6
##am__append_11 = -D_XPG4_2

# Set flags for Sun CC.
#am__append_12 = -erroff=E_EMPTY_DECLARATION

# Set _LINUX_SOURCE_COMPAT for AIX for malloc(0).
#am__append_13 = -D_LINUX_SOURCE_COMPAT=1

# Set flags for NetBSD.
#am__append_14 = -D_OPENBSD_SOURCE

# Set flags for Haiku.
#am__append_15 = -D_BSD_SOURCE

# Set flags for Cygwin.
#am__append_16 = -DTMUX_SOCK_PERM=0

# Add compat file for forkpty.
#am__append_17 = compat/forkpty-freebsd.c

# Add compat file for systemd.
#am__append_18 = compat/systemd.c

# Add compat file for utf8proc.
#am__append_19 = compat/utf8proc.c

# Enable sixel support.
#am__append_20 = image.c image-sixel.c
#check_PROGRAMS = fuzz/input-fuzzer$(EXEEXT) \
#	fuzz/cmd-parse-fuzzer$(EXEEXT) \
#	fuzz/format-fuzzer$(EXEEXT) \
#	fuzz/style-fuzzer$(EXEEXT)
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
LIBOBJDIR = compat/
am__dirstamp = $(am__leading_dot)dirstamp
fuzz_cmd_parse_fuzzer_SOURCES = fuzz/cmd-parse-fuzzer.c
fuzz_cmd_parse_fuzzer_OBJECTS = fuzz/cmd-parse-fuzzer.$(OBJEXT)
#fuzz_cmd_parse_fuzzer_DEPENDENCIES = $(LDADD)
fuzz_cmd_parse_fuzzer_LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(fuzz_cmd_parse_fuzzer_LDFLAGS) $(LDFLAGS) -o $@
fuzz_format_fuzzer_SOURCES = fuzz/format-fuzzer.c
fuzz_format_fuzzer_OBJECTS = fuzz/format-fuzzer.$(OBJEXT)
#fuzz_format_fuzzer_DEPENDENCIES = $(LDADD)
fuzz_format_fuzzer_LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(fuzz_format_fuzzer_LDFLAGS) $(LDFLAGS) -o $@
fuzz_input_fuzzer_SOURCES = fuzz/input-fuzzer.c
fuzz_input_fuzzer_OBJECTS = fuzz/input-fuzzer.$(OBJEXT)
#fuzz_input_fuzzer_DEPENDENCIES = $(LDADD)
fuzz_input_fuzzer_LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(fuzz_input_fuzzer_LDFLAGS) $(LDFLAGS) -o $@
fuzz_style_fuzzer_SOURCES = fuzz/style-fuzzer.c
fuzz_style_fuzzer_OBJECTS = fuzz/style-fuzzer.$(OBJEXT)
#fuzz_style_fuzzer_DEPENDENCIES = $(LDADD)
fuzz_style_fuzzer_LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(fuzz_style_fuzzer_LDFLAGS) $(LDFLAGS) -o $@
am__dist_tmux_SOURCES_DIST = alerts.c arguments.c attributes.c cfg.c \
	client.c cmd-attach-session.c cmd-bind-key.c cmd-break-pane.c \
	cmd-capture-pane.c cmd-choose-tree.c cmd-command-prompt.c \
	cmd-confirm-before.c cmd-copy-mode.c cmd-detach-client.c \
	cmd-display-menu.c cmd-display-message.c cmd-display-panes.c \
	cmd-find-window.c cmd-find.c cmd-if-shell.c cmd-join-pane.c \
	cmd-kill-pane.c cmd-kill-server.c cmd-kill-session.c \
	cmd-kill-window.c cmd-list-buffers.c cmd-list-clients.c \
	cmd-list-commands.c cmd-list-keys.c cmd-list-panes.c \
	cmd-list-sessions.c cmd-list-windows.c cmd-load-buffer.c \
	cmd-lock-server.c cmd-move-window.c cmd-new-session.c \
	cmd-new-window.c cmd-parse.y cmd-paste-buffer.c \
	cmd-pipe-pane.c cmd-queue.c cmd-refresh-client.c \
	cmd-rename-session.c cmd-rename-window.c cmd-resize-pane.c \
	cmd-resize-window.c cmd-respawn-pane.c cmd-respawn-window.c \
	cmd-rotate-window.c cmd-run-shell.c cmd-save-buffer.c \
	cmd-select-layout.c cmd-select-pane.c cmd-select-window.c \
	cmd-send-keys.c cmd-server-access.c cmd-set-buffer.c \
	cmd-set-environment.c cmd-set-option.c cmd-show-environment.c \
	cmd-show-messages.c cmd-show-options.c \
	cmd-show-prompt-history.c cmd-source-file.c cmd-split-window.c \
	cmd-swap-pane.c cmd-swap-window.c cmd-switch-client.c \
	cmd-unbind-key.c cmd-wait-for.c cmd.c colour.c compat.h \
	control-notify.c control.c environ.c file.c format.c \
	format-draw.c grid-reader.c grid-view.c grid.c hyperlinks.c \
	input-keys.c input.c job.c key-bindings.c key-string.c \
	layout-custom.c layout-set.c layout.c log.c menu.c mode-tree.c \
	names.c notify.c options-table.c options.c paste.c popup.c \
	proc.c regsub.c resize.c screen-redraw.c screen-write.c \
	screen.c server-acl.c server-client.c server-fn.c server.c \
	session.c sort.c spawn.c status.c style.c tmux.c tmux.h \
	tmux-protocol.h tty-acs.c tty-draw.c tty-features.c tty-keys.c \
	tty-term.c tty.c utf8-combined.c utf8.c window-border.c \
	window-buffer.c window-client.c window-clock.c window-copy.c \
	window-customize.c window-tree.c window-visible.c window.c \
	xmalloc.c xmalloc.h image.c image-sixel.c
#am__objects_1 = image.$(OBJEXT) \
#	image-sixel.$(OBJEXT)
dist_tmux_OBJECTS = alerts.$(OBJEXT) arguments.$(OBJEXT) \
	attributes.$(OBJEXT) cfg.$(OBJEXT) client.$(OBJEXT) \
	cmd-attach-session.$(OBJEXT) cmd-bind-key.$(OBJEXT) \
	cmd-break-pane.$(OBJEXT) cmd-capture-pane.$(OBJEXT) \
	cmd-choose-tree.$(OBJEXT) cmd-command-prompt.$(OBJEXT) \
	cmd-confirm-before.$(OBJEXT) cmd-copy-mode.$(OBJEXT) \
	cmd-detach-client.$(OBJEXT) cmd-display-menu.$(OBJEXT) \
	cmd-display-message.$(OBJEXT) cmd-display-panes.$(OBJEXT) \
	cmd-find-window.$(OBJEXT) cmd-find.$(OBJEXT) \
	cmd-if-shell.$(OBJEXT) cmd-join-pane.$(OBJEXT) \
	cmd-kill-pane.$(OBJEXT) cmd-kill-server.$(OBJEXT) \
	cmd-kill-session.$(OBJEXT) cmd-kill-window.$(OBJEXT) \
	cmd-list-buffers.$(OBJEXT) cmd-list-clients.$(OBJEXT) \
	cmd-list-commands.$(OBJEXT) cmd-list-keys.$(OBJEXT) \
	cmd-list-panes.$(OBJEXT) cmd-list-sessions.$(OBJEXT) \
	cmd-list-windows.$(OBJEXT) cmd-load-buffer.$(OBJEXT) \
	cmd-lock-server.$(OBJEXT) cmd-move-window.$(OBJEXT) \
	cmd-new-session.$(OBJEXT) cmd-new-window.$(OBJEXT) \
	cmd-parse.$(OBJEXT) cmd-paste-buffer.$(OBJEXT) \
	cmd-pipe-pane.$(OBJEXT) cmd-queue.$(OBJEXT) \
	cmd-refresh-client.$(OBJEXT) cmd-rename-session.$(OBJEXT) \
	cmd-rename-window.$(OBJEXT) cmd-resize-pane.$(OBJEXT) \
	cmd-resize-window.$(OBJEXT) cmd-respawn-pane.$(OBJEXT) \
	cmd-respawn-window.$(OBJEXT) cmd-rotate-window.$(OBJEXT) \
	cmd-run-shell.$(OBJEXT) cmd-save-buffer.$(OBJEXT) \
	cmd-select-layout.$(OBJEXT) cmd-select-pane.$(OBJEXT) \
	cmd-select-window.$(OBJEXT) cmd-send-keys.$(OBJEXT) \
	cmd-server-access.$(OBJEXT) cmd-set-buffer.$(OBJEXT) \
	cmd-set-environment.$(OBJEXT) cmd-set-option.$(OBJEXT) \
	cmd-show-environment.$(OBJEXT) cmd-show-messages.$(OBJEXT) \
	cmd-show-options.$(OBJEXT) cmd-show-prompt-history.$(OBJEXT) \
	cmd-source-file.$(OBJEXT) cmd-split-window.$(OBJEXT) \
	cmd-swap-pane.$(OBJEXT) cmd-swap-window.$(OBJEXT) \
	cmd-switch-client.$(OBJEXT) cmd-unbind-key.$(OBJEXT) \
	cmd-wait-for.$(OBJEXT) cmd.$(OBJEXT) colour.$(OBJEXT) \
	control-notify.$(OBJEXT) control.$(OBJEXT) environ.$(OBJEXT) \
	file.$(OBJEXT) format.$(OBJEXT) format-draw.$(OBJEXT) \
	grid-reader.$(OBJEXT) grid-view.$(OBJEXT) grid.$(OBJEXT) \
	hyperlinks.$(OBJEXT) input-keys.$(OBJEXT) input.$(OBJEXT) \
	job.$(OBJEXT) key-bindings.$(OBJEXT) key-string.$(OBJEXT) \
	layout-custom.$(OBJEXT) layout-set.$(OBJEXT) layout.$(OBJEXT) \
	log.$(OBJEXT) menu.$(OBJEXT) mode-tree.$(OBJEXT) \
	names.$(OBJEXT) notify.$(OBJEXT) options-table.$(OBJEXT) \
	options.$(OBJEXT) paste.$(OBJEXT) popup.$(OBJEXT) \
	proc.$(OBJEXT) regsub.$(OBJEXT) resize.$(OBJEXT) \
	screen-redraw.$(OBJEXT) screen-write.$(OBJEXT) \
	screen.$(OBJEXT) server-acl.$(OBJEXT) server-client.$(OBJEXT) \
	server-fn.$(OBJEXT) server.$(OBJEXT) session.$(OBJEXT) \
	sort.$(OBJEXT) spawn.$(OBJEXT) status.$(OBJEXT) \
	style.$(OBJEXT) tmux.$(OBJEXT) tty-acs.$(OBJEXT) \
	tty-draw.$(OBJEXT) tty-features.$(OBJEXT) tty-keys.$(OBJEXT) \
	tty-term.$(OBJEXT) tty.$(OBJEXT) utf8-combined.$(OBJEXT) \
	utf8.$(OBJEXT) window-border.$(OBJEXT) window-buffer.$(OBJEXT) \
	window-client.$(OBJEXT) window-clock.$(OBJEXT) \
	window-copy.$(OBJEXT) window-customize.$(OBJEXT) \
	window-tree.$(OBJEXT) window-visible.$(OBJEXT) \
	window.$(OBJEXT) xmalloc.$(OBJEXT) $(am__objects_1)
#am__objects_2 =  \
#	compat/forkpty-freebsd.$(OBJEXT)
#am__objects_3 = compat/systemd.$(OBJEXT)
#am__objects_4 = compat/utf8proc.$(OBJEXT)
nodist_tmux_OBJECTS = osdep-freebsd.$(OBJEXT) $(am__objects_2) \
	$(am__objects_3) $(am__objects_4)
tmux_OBJECTS = $(dist_tmux_OBJECTS) $(nodist_tmux_OBJECTS)
tmux_LDADD = $(LDADD)
tmux_DEPENDENCIES = $(LIBOBJS)
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/etc/depcomp
am__maybe_remake_depfiles = depfiles
am__depfiles_remade = ./$(DEPDIR)/alerts.Po ./$(DEPDIR)/arguments.Po \
	./$(DEPDIR)/attributes.Po ./$(DEPDIR)/cfg.Po \
	./$(DEPDIR)/client.Po ./$(DEPDIR)/cmd-attach-session.Po \
	./$(DEPDIR)/cmd-bind-key.Po ./$(DEPDIR)/cmd-break-pane.Po \
	./$(DEPDIR)/cmd-capture-pane.Po ./$(DEPDIR)/cmd-choose-tree.Po \
	./$(DEPDIR)/cmd-command-prompt.Po \
	./$(DEPDIR)/cmd-confirm-before.Po ./$(DEPDIR)/cmd-copy-mode.Po \
	./$(DEPDIR)/cmd-detach-client.Po \
	./$(DEPDIR)/cmd-display-menu.Po \
	./$(DEPDIR)/cmd-display-message.Po \
	./$(DEPDIR)/cmd-display-panes.Po \
	./$(DEPDIR)/cmd-find-window.Po ./$(DEPDIR)/cmd-find.Po \
	./$(DEPDIR)/cmd-if-shell.Po ./$(DEPDIR)/cmd-join-pane.Po \
	./$(DEPDIR)/cmd-kill-pane.Po ./$(DEPDIR)/cmd-kill-server.Po \
	./$(DEPDIR)/cmd-kill-session.Po ./$(DEPDIR)/cmd-kill-window.Po \
	./$(DEPDIR)/cmd-list-buffers.Po \
	./$(DEPDIR)/cmd-list-clients.Po \
	./$(DEPDIR)/cmd-list-commands.Po ./$(DEPDIR)/cmd-list-keys.Po \
	./$(DEPDIR)/cmd-list-panes.Po ./$(DEPDIR)/cmd-list-sessions.Po \
	./$(DEPDIR)/cmd-list-windows.Po ./$(DEPDIR)/cmd-load-buffer.Po \
	./$(DEPDIR)/cmd-lock-server.Po ./$(DEPDIR)/cmd-move-window.Po \
	./$(DEPDIR)/cmd-new-session.Po ./$(DEPDIR)/cmd-new-window.Po \
	./$(DEPDIR)/cmd-parse.Po ./$(DEPDIR)/cmd-paste-buffer.Po \
	./$(DEPDIR)/cmd-pipe-pane.Po ./$(DEPDIR)/cmd-queue.Po \
	./$(DEPDIR)/cmd-refresh-client.Po \
	./$(DEPDIR)/cmd-rename-session.Po \
	./$(DEPDIR)/cmd-rename-window.Po \
	./$(DEPDIR)/cmd-resize-pane.Po \
	./$(DEPDIR)/cmd-resize-window.Po \
	./$(DEPDIR)/cmd-respawn-pane.Po \
	./$(DEPDIR)/cmd-respawn-window.Po \
	./$(DEPDIR)/cmd-rotate-window.Po ./$(DEPDIR)/cmd-run-shell.Po \
	./$(DEPDIR)/cmd-save-buffer.Po \
	./$(DEPDIR)/cmd-select-layout.Po \
	./$(DEPDIR)/cmd-select-pane.Po \
	./$(DEPDIR)/cmd-select-window.Po ./$(DEPDIR)/cmd-send-keys.Po \
	./$(DEPDIR)/cmd-server-access.Po ./$(DEPDIR)/cmd-set-buffer.Po \
	./$(DEPDIR)/cmd-set-environment.Po \
	./$(DEPDIR)/cmd-set-option.Po \
	./$(DEPDIR)/cmd-show-environment.Po \
	./$(DEPDIR)/cmd-show-messages.Po \
	./$(DEPDIR)/cmd-show-options.Po \
	./$(DEPDIR)/cmd-show-prompt-history.Po \
	./$(DEPDIR)/cmd-source-file.Po ./$(DEPDIR)/cmd-split-window.Po \
	./$(DEPDIR)/cmd-swap-pane.Po ./$(DEPDIR)/cmd-swap-window.Po \
	./$(DEPDIR)/cmd-switch-client.Po ./$(DEPDIR)/cmd-unbind-key.Po \
	./$(DEPDIR)/cmd-wait-for.Po ./$(DEPDIR)/cmd.Po \
	./$(DEPDIR)/colour.Po ./$(DEPDIR)/control-notify.Po \
	./$(DEPDIR)/control.Po ./$(DEPDIR)/environ.Po \
	./$(DEPDIR)/file.Po ./$(DEPDIR)/format-draw.Po \
	./$(DEPDIR)/format.Po ./$(DEPDIR)/grid-reader.Po \
	./$(DEPDIR)/grid-view.Po ./$(DEPDIR)/grid.Po \
	./$(DEPDIR)/hyperlinks.Po ./$(DEPDIR)/image-sixel.Po \
	./$(DEPDIR)/image.Po ./$(DEPDIR)/input-keys.Po \
	./$(DEPDIR)/input.Po ./$(DEPDIR)/job.Po \
	./$(DEPDIR)/key-bindings.Po ./$(DEPDIR)/key-string.Po \
	./$(DEPDIR)/layout-custom.Po ./$(DEPDIR)/layout-set.Po \
	./$(DEPDIR)/layout.Po ./$(DEPDIR)/log.Po ./$(DEPDIR)/menu.Po \
	./$(DEPDIR)/mode-tree.Po ./$(DEPDIR)/names.Po \
	./$(DEPDIR)/notify.Po ./$(DEPDIR)/options-table.Po \
	./$(DEPDIR)/options.Po ./$(DEPDIR)/osdep-freebsd.Po \
	./$(DEPDIR)/paste.Po ./$(DEPDIR)/popup.Po ./$(DEPDIR)/proc.Po \
	./$(DEPDIR)/regsub.Po ./$(DEPDIR)/resize.Po \
	./$(DEPDIR)/screen-redraw.Po ./$(DEPDIR)/screen-write.Po \
	./$(DEPDIR)/screen.Po ./$(DEPDIR)/server-acl.Po \
	./$(DEPDIR)/server-client.Po ./$(DEPDIR)/server-fn.Po \
	./$(DEPDIR)/server.Po ./$(DEPDIR)/session.Po \
	./$(DEPDIR)/sort.Po ./$(DEPDIR)/spawn.Po ./$(DEPDIR)/status.Po \
	./$(DEPDIR)/style.Po ./$(DEPDIR)/tmux.Po \
	./$(DEPDIR)/tty-acs.Po ./$(DEPDIR)/tty-draw.Po \
	./$(DEPDIR)/tty-features.Po ./$(DEPDIR)/tty-keys.Po \
	./$(DEPDIR)/tty-term.Po ./$(DEPDIR)/tty.Po \
	./$(DEPDIR)/utf8-combined.Po ./$(DEPDIR)/utf8.Po \
	./$(DEPDIR)/window-border.Po ./$(DEPDIR)/window-buffer.Po \
	./$(DEPDIR)/window-client.Po ./$(DEPDIR)/window-clock.Po \
	./$(DEPDIR)/window-copy.Po ./$(DEPDIR)/window-customize.Po \
	./$(DEPDIR)/window-tree.Po ./$(DEPDIR)/window-visible.Po \
	./$(DEPDIR)/window.Po ./$(DEPDIR)/xmalloc.Po \
	compat/$(DEPDIR)/asprintf.Po compat/$(DEPDIR)/base64.Po \
	compat/$(DEPDIR)/cfmakeraw.Po \
	compat/$(DEPDIR)/clock_gettime.Po \
	compat/$(DEPDIR)/closefrom.Po \
	compat/$(DEPDIR)/daemon-darwin.Po compat/$(DEPDIR)/daemon.Po \
	compat/$(DEPDIR)/err.Po compat/$(DEPDIR)/explicit_bzero.Po \
	compat/$(DEPDIR)/fdforkpty.Po compat/$(DEPDIR)/fgetln.Po \
	compat/$(DEPDIR)/forkpty-freebsd.Po \
	compat/$(DEPDIR)/freezero.Po \
	compat/$(DEPDIR)/getdtablecount.Po \
	compat/$(DEPDIR)/getdtablesize.Po compat/$(DEPDIR)/getline.Po \
	compat/$(DEPDIR)/getopt_long.Po compat/$(DEPDIR)/getpeereid.Po \
	compat/$(DEPDIR)/getprogname.Po compat/$(DEPDIR)/htonll.Po \
	compat/$(DEPDIR)/imsg-buffer.Po compat/$(DEPDIR)/imsg.Po \
	compat/$(DEPDIR)/memmem.Po compat/$(DEPDIR)/ntohll.Po \
	compat/$(DEPDIR)/reallocarray.Po \
	compat/$(DEPDIR)/recallocarray.Po compat/$(DEPDIR)/setenv.Po \
	compat/$(DEPDIR)/setproctitle.Po \
	compat/$(DEPDIR)/strcasestr.Po compat/$(DEPDIR)/strlcat.Po \
	compat/$(DEPDIR)/strlcpy.Po compat/$(DEPDIR)/strndup.Po \
	compat/$(DEPDIR)/strnlen.Po compat/$(DEPDIR)/strsep.Po \
	compat/$(DEPDIR)/strtonum.Po compat/$(DEPDIR)/systemd.Po \
	compat/$(DEPDIR)/unvis.Po compat/$(DEPDIR)/utf8proc.Po \
	compat/$(DEPDIR)/vis.Po fuzz/$(DEPDIR)/cmd-parse-fuzzer.Po \
	fuzz/$(DEPDIR)/format-fuzzer.Po fuzz/$(DEPDIR)/input-fuzzer.Po \
	fuzz/$(DEPDIR)/style-fuzzer.Po
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
am__yacc_c2h = sed -e s/cc$$/hh/ -e s/cpp$$/hpp/ -e s/cxx$$/hxx/ \
		   -e s/c++$$/h++/ -e s/c$$/h/
YACCCOMPILE = $(YACC) $(AM_YFLAGS) $(YFLAGS)
AM_V_YACC = $(am__v_YACC_$(V))
am__v_YACC_ = $(am__v_YACC_$(AM_DEFAULT_VERBOSITY))
am__v_YACC_0 = @echo "  YACC    " $@;
am__v_YACC_1 = 
YLWRAP = $(top_srcdir)/etc/ylwrap
SOURCES = fuzz/cmd-parse-fuzzer.c fuzz/format-fuzzer.c \
	fuzz/input-fuzzer.c fuzz/style-fuzzer.c $(dist_tmux_SOURCES) \
	$(nodist_tmux_SOURCES) $(dist_EXTRA_tmux_SOURCES)
DIST_SOURCES = fuzz/cmd-parse-fuzzer.c fuzz/format-fuzzer.c \
	fuzz/input-fuzzer.c fuzz/style-fuzzer.c \
	$(am__dist_tmux_SOURCES_DIST) $(dist_EXTRA_tmux_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP)
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
AM_RECURSIVE_TARGETS = cscope
am__DIST_COMMON = $(srcdir)/Makefile.in \
	$(top_srcdir)/compat/asprintf.c $(top_srcdir)/compat/base64.c \
	$(top_srcdir)/compat/cfmakeraw.c \
	$(top_srcdir)/compat/clock_gettime.c \
	$(top_srcdir)/compat/closefrom.c \
	$(top_srcdir)/compat/daemon-darwin.c \
	$(top_srcdir)/compat/daemon.c $(top_srcdir)/compat/err.c \
	$(top_srcdir)/compat/explicit_bzero.c \
	$(top_srcdir)/compat/fdforkpty.c $(top_srcdir)/compat/fgetln.c \
	$(top_srcdir)/compat/freezero.c \
	$(top_srcdir)/compat/getdtablecount.c \
	$(top_srcdir)/compat/getdtablesize.c \
	$(top_srcdir)/compat/getline.c \
	$(top_srcdir)/compat/getopt_long.c \
	$(top_srcdir)/compat/getpeereid.c \
	$(top_srcdir)/compat/getprogname.c \
	$(top_srcdir)/compat/htonll.c \
	$(top_srcdir)/compat/imsg-buffer.c $(top_srcdir)/compat/imsg.c \
	$(top_srcdir)/compat/memmem.c $(top_srcdir)/compat/ntohll.c \
	$(top_srcdir)/compat/reallocarray.c \
	$(top_srcdir)/compat/recallocarray.c \
	$(top_srcdir)/compat/setenv.c \
	$(top_srcdir)/compat/setproctitle.c \
	$(top_srcdir)/compat/strcasestr.c \
	$(top_srcdir)/compat/strlcat.c $(top_srcdir)/compat/strlcpy.c \
	$(top_srcdir)/compat/strndup.c $(top_srcdir)/compat/strnlen.c \
	$(top_srcdir)/compat/strsep.c $(top_srcdir)/compat/strtonum.c \
	$(top_srcdir)/compat/unvis.c $(top_srcdir)/compat/vis.c \
	$(top_srcdir)/etc/compile $(top_srcdir)/etc/config.guess \
	$(top_srcdir)/etc/config.sub $(top_srcdir)/etc/depcomp \
	$(top_srcdir)/etc/install-sh $(top_srcdir)/etc/missing \
	$(top_srcdir)/etc/ylwrap COPYING README cmd-parse.c \
	etc/compile etc/config.guess etc/config.sub etc/depcomp \
	etc/install-sh etc/missing etc/ylwrap
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -700 -exec chmod u+rwx {} ';' \
      ; rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = -9
DIST_TARGETS = dist-gzip
# Exists only to be overridden by the user if desired.
AM_DISTCHECK_DVI_TARGET = dvi
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = \
  find . \( -type f -a \! \
            \( -name .nfs* -o -name .smb* -o -name .__afs* \) \) -print
ACLOCAL = ${SHELL} '/home/n6tadam/tmux-portable/etc/missing' aclocal-1.18
AMTAR = $${TAR-tar}
AM_CFLAGS =  $(am__append_1) $(am__append_2) \
	$(am__append_3) $(am__append_4) $(am__append_5) \
	$(am__append_8) $(am__append_12)

# Preprocessor flags.
AM_CPPFLAGS =  -I/usr/local/include   \
	-DTMUX_VERSION='"next-3.7"' \
	-DTMUX_CONF='"$(sysconfdir)/tmux.conf:~/.tmux.conf:$$XDG_CONFIG_HOME/tmux/tmux.conf:~/.config/tmux/tmux.conf"' \
	-DTMUX_LOCK_CMD='"lock -np"' \
	-DTMUX_TERM='"tmux-256color"' $(am__append_6) $(am__append_7) \
	$(am__append_10) $(am__append_11) $(am__append_13) \
	$(am__append_14) $(am__append_15) $(am__append_16)
AM_DEFAULT_VERBOSITY = 1
AM_LDFLAGS =  $(am__append_9)
AUTOCONF = ${SHELL} '/home/n6tadam/tmux-portable/etc/missing' autoconf
AUTOHEADER = ${SHELL} '/home/n6tadam/tmux-portable/etc/missing' autoheader
AUTOMAKE = ${SHELL} '/home/n6tadam/tmux-portable/etc/missing' automake-1.18
AWK = nawk
CC = cc
CCDEPMODE = depmode=gcc3
CFLAGS = 
CPP = cc -E
CPPFLAGS = 
CSCOPE = cscope
CTAGS = ctags
CYGPATH_W = echo
DEFAULT_LOCK_CMD = lock -np
DEFAULT_TERM = tmux-256color
DEFS = -DPACKAGE_NAME=\"tmux\" -DPACKAGE_TARNAME=\"tmux\" -DPACKAGE_VERSION=\"next-3.7\" -DPACKAGE_STRING=\"tmux\ next-3.7\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tmux\" -DVERSION=\"next-3.7\" -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DHAVE_WCHAR_H=1 -DSTDC_HEADERS=1 -D_ALL_SOURCE=1 -D_COSMO_SOURCE=1 -D_DARWIN_C_SOURCE=1 -D_GNU_SOURCE=1 -D_HPUX_ALT_XOPEN_SOCKET_API=1 -D_NETBSD_SOURCE=1 -D_OPENBSD_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D__STDC_WANT_IEC_60559_ATTRIBS_EXT__=1 -D__STDC_WANT_IEC_60559_BFP_EXT__=1 -D__STDC_WANT_IEC_60559_DFP_EXT__=1 -D__STDC_WANT_IEC_60559_EXT__=1 -D__STDC_WANT_IEC_60559_FUNCS_EXT__=1 -D__STDC_WANT_IEC_60559_TYPES_EXT__=1 -D__STDC_WANT_LIB_EXT2__=1 -D__STDC_WANT_MATH_SPEC_FUNCS__=1 -D_TANDEM_SOURCE=1 -D__EXTENSIONS__=1 -DHAVE_BITSTRING_H=1 -DHAVE_DIRENT_H=1 -DHAVE_FCNTL_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_LIBPROC_H=1 -DHAVE_LIBUTIL_H=1 -DHAVE_PATHS_H=1 -DHAVE_STDINT_H=1 -DHAVE_SYS_TREE_H=1 -DHAVE_SYS_SIGNAME=1 -DHAVE_LIBM=1 -DHAVE_DIRFD=1 -DHAVE_FLOCK=1 -DHAVE_SYSCONF=1 -DHAVE_ASPRINTF=1 -DHAVE_CFMAKERAW=1 -DHAVE_CLOCK_GETTIME=1 -DHAVE_CLOSEFROM=1 -DHAVE_EXPLICIT_BZERO=1 -DHAVE_FGETLN=1 -DHAVE_GETDTABLESIZE=1 -DHAVE_GETPEEREID=1 -DHAVE_GETLINE=1 -DHAVE_GETPROGNAME=1 -DHAVE_MEMMEM=1 -DHAVE_SETENV=1 -DHAVE_SETPROCTITLE=1 -DHAVE_STRCASESTR=1 -DHAVE_STRLCAT=1 -DHAVE_STRLCPY=1 -DHAVE_STRNDUP=1 -DHAVE_STRSEP=1 -DHAVE_STRTONUM=1 -DHAVE_EVENT2_EVENT_H=1 -DHAVE_NCURSES_H=1 -DHAVE_TIPARM=1 -DHAVE_TIPARM_S=1 -DHAVE_B64_NTOP=1 -DHAVE_LIBXNET=1 -DHAVE_DAEMON=1 -DHAVE_FORKPTY=1 -DHAVE_QUEUE_H=1 -DHAVE___PROGNAME=1
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /usr/bin/grep -E
ETAGS = etags
EXEEXT = 
FUZZING_LIBS = 
GREP = /usr/bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
JEMALLOC_CFLAGS = 
JEMALLOC_LIBS = 
LDFLAGS = 
LIBEVENT_CFLAGS = 
LIBEVENT_CORE_CFLAGS = -I/usr/local/include
LIBEVENT_CORE_LIBS = -L/usr/local/lib -levent_core
LIBEVENT_LIBS = 
LIBNCURSESW_CFLAGS = 
LIBNCURSESW_LIBS = 
LIBNCURSES_CFLAGS = 
LIBNCURSES_LIBS = 
LIBOBJS =  ${LIBOBJDIR}freezero$U.o ${LIBOBJDIR}getdtablecount$U.o ${LIBOBJDIR}htonll$U.o ${LIBOBJDIR}ntohll$U.o ${LIBOBJDIR}recallocarray$U.o ${LIBOBJDIR}getopt_long$U.o ${LIBOBJDIR}imsg$U.o ${LIBOBJDIR}imsg-buffer$U.o ${LIBOBJDIR}vis$U.o ${LIBOBJDIR}unvis$U.o ${LIBOBJDIR}fdforkpty$U.o
LIBS = -lutil -lxnet -fstack-protector-strong -ltinfow -L/usr/local/lib -levent_core -lm 
LIBTINFOW_CFLAGS = 
LIBTINFOW_LIBS = -fstack-protector-strong -ltinfow
LIBTINFO_CFLAGS = 
LIBTINFO_LIBS = 
LIBUTF8PROC_CFLAGS = 
LIBUTF8PROC_LIBS = 
LTLIBOBJS =  ${LIBOBJDIR}freezero$U.lo ${LIBOBJDIR}getdtablecount$U.lo ${LIBOBJDIR}htonll$U.lo ${LIBOBJDIR}ntohll$U.lo ${LIBOBJDIR}recallocarray$U.lo ${LIBOBJDIR}getopt_long$U.lo ${LIBOBJDIR}imsg$U.lo ${LIBOBJDIR}imsg-buffer$U.lo ${LIBOBJDIR}vis$U.lo ${LIBOBJDIR}unvis$U.lo ${LIBOBJDIR}fdforkpty$U.lo
MAKEINFO = ${SHELL} '/home/n6tadam/tmux-portable/etc/missing' makeinfo
MANFORMAT = mdoc
MKDIR_P = /usr/local/bin/gmkdir -p
OBJEXT = o
PACKAGE = tmux
PACKAGE_BUGREPORT = 
PACKAGE_NAME = tmux
PACKAGE_STRING = tmux next-3.7
PACKAGE_TARNAME = tmux
PACKAGE_URL = 
PACKAGE_VERSION = next-3.7
PATH_SEPARATOR = :
PKG_CONFIG = /usr/local/bin/pkg-config
PKG_CONFIG_LIBDIR = 
PKG_CONFIG_PATH = 
PLATFORM = freebsd
SET_MAKE = 
SHELL = /bin/sh
STRIP = 
SYSTEMD_CFLAGS = 
SYSTEMD_LIBS = 
VERSION = next-3.7
XOPEN_DEFINES = 
YACC = byacc
YFLAGS = 
abs_builddir = /home/n6tadam/tmux-portable
abs_srcdir = /home/n6tadam/tmux-portable
abs_top_builddir = /home/n6tadam/tmux-portable
abs_top_srcdir = /home/n6tadam/tmux-portable
ac_ct_CC = 
am__include = include
am__leading_dot = .
am__quote = 
am__rm_f_notfound = 
am__tar = tar --format=ustar -chf - "$$tardir"
am__untar = tar -xf -
am__xargs_n = xargs -n
bindir = ${exec_prefix}/bin
build = amd64-unknown-freebsd15.0
build_alias = 
build_cpu = amd64
build_os = freebsd15.0
build_vendor = unknown
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
found_vlock = 
found_yacc = yes
host = amd64-unknown-freebsd15.0
host_alias = 
host_cpu = amd64
host_os = freebsd15.0
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/n6tadam/tmux-portable/etc/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
runstatedir = ${localstatedir}/run
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = /etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
CLEANFILES = tmux.1.mdoc tmux.1.man cmd-parse.c

# Distribution tarball options.
EXTRA_DIST = \
	CHANGES README README.ja COPYING example_tmux.conf \
	osdep-*.c mdoc2man.awk tmux.1

dist_EXTRA_tmux_SOURCES = compat/*.[ch]

# Additional object files.
LDADD = $(LIBOBJS)

# List of sources.
dist_tmux_SOURCES = alerts.c arguments.c attributes.c cfg.c client.c \
	cmd-attach-session.c cmd-bind-key.c cmd-break-pane.c \
	cmd-capture-pane.c cmd-choose-tree.c cmd-command-prompt.c \
	cmd-confirm-before.c cmd-copy-mode.c cmd-detach-client.c \
	cmd-display-menu.c cmd-display-message.c cmd-display-panes.c \
	cmd-find-window.c cmd-find.c cmd-if-shell.c cmd-join-pane.c \
	cmd-kill-pane.c cmd-kill-server.c cmd-kill-session.c \
	cmd-kill-window.c cmd-list-buffers.c cmd-list-clients.c \
	cmd-list-commands.c cmd-list-keys.c cmd-list-panes.c \
	cmd-list-sessions.c cmd-list-windows.c cmd-load-buffer.c \
	cmd-lock-server.c cmd-move-window.c cmd-new-session.c \
	cmd-new-window.c cmd-parse.y cmd-paste-buffer.c \
	cmd-pipe-pane.c cmd-queue.c cmd-refresh-client.c \
	cmd-rename-session.c cmd-rename-window.c cmd-resize-pane.c \
	cmd-resize-window.c cmd-respawn-pane.c cmd-respawn-window.c \
	cmd-rotate-window.c cmd-run-shell.c cmd-save-buffer.c \
	cmd-select-layout.c cmd-select-pane.c cmd-select-window.c \
	cmd-send-keys.c cmd-server-access.c cmd-set-buffer.c \
	cmd-set-environment.c cmd-set-option.c cmd-show-environment.c \
	cmd-show-messages.c cmd-show-options.c \
	cmd-show-prompt-history.c cmd-source-file.c cmd-split-window.c \
	cmd-swap-pane.c cmd-swap-window.c cmd-switch-client.c \
	cmd-unbind-key.c cmd-wait-for.c cmd.c colour.c compat.h \
	control-notify.c control.c environ.c file.c format.c \
	format-draw.c grid-reader.c grid-view.c grid.c hyperlinks.c \
	input-keys.c input.c job.c key-bindings.c key-string.c \
	layout-custom.c layout-set.c layout.c log.c menu.c mode-tree.c \
	names.c notify.c options-table.c options.c paste.c popup.c \
	proc.c regsub.c resize.c screen-redraw.c screen-write.c \
	screen.c server-acl.c server-client.c server-fn.c server.c \
	session.c sort.c spawn.c status.c style.c tmux.c tmux.h \
	tmux-protocol.h tty-acs.c tty-draw.c tty-features.c tty-keys.c \
	tty-term.c tty.c utf8-combined.c utf8.c window-border.c \
	window-buffer.c window-client.c window-clock.c window-copy.c \
	window-customize.c window-tree.c window-visible.c window.c \
	xmalloc.c xmalloc.h $(am__append_20)
nodist_tmux_SOURCES = osdep-freebsd.c $(am__append_17) \
	$(am__append_18) $(am__append_19)
#fuzz_input_fuzzer_LDFLAGS = $(FUZZING_LIBS)
#fuzz_input_fuzzer_LDADD = $(LDADD) $(tmux_OBJECTS)
#fuzz_cmd_parse_fuzzer_LDFLAGS = $(FUZZING_LIBS)
#fuzz_cmd_parse_fuzzer_LDADD = $(LDADD) $(tmux_OBJECTS)
#fuzz_format_fuzzer_LDFLAGS = $(FUZZING_LIBS)
#fuzz_format_fuzzer_LDADD = $(LDADD) $(tmux_OBJECTS)
#fuzz_style_fuzzer_LDFLAGS = $(FUZZING_LIBS)
#fuzz_style_fuzzer_LDADD = $(LDADD) $(tmux_OBJECTS)
all: all-am

.SUFFIXES:
.SUFFIXES: .c .o .obj .y
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && $(am__rm_f) $$files

clean-binPROGRAMS:
	-$(am__rm_f) $(bin_PROGRAMS)

clean-checkPROGRAMS:
	-$(am__rm_f) $(check_PROGRAMS)
compat/$(am__dirstamp):
	@$(MKDIR_P) compat/
	@: >>compat/$(am__dirstamp)
compat/asprintf.$(OBJEXT): compat/$(am__dirstamp)
compat/base64.$(OBJEXT): compat/$(am__dirstamp)
compat/cfmakeraw.$(OBJEXT): compat/$(am__dirstamp)
compat/clock_gettime.$(OBJEXT): compat/$(am__dirstamp)
compat/closefrom.$(OBJEXT): compat/$(am__dirstamp)
compat/daemon-darwin.$(OBJEXT): compat/$(am__dirstamp)
compat/daemon.$(OBJEXT): compat/$(am__dirstamp)
compat/err.$(OBJEXT): compat/$(am__dirstamp)
compat/explicit_bzero.$(OBJEXT): compat/$(am__dirstamp)
compat/fdforkpty.$(OBJEXT): compat/$(am__dirstamp)
compat/fgetln.$(OBJEXT): compat/$(am__dirstamp)
compat/freezero.$(OBJEXT): compat/$(am__dirstamp)
compat/getdtablecount.$(OBJEXT): compat/$(am__dirstamp)
compat/getdtablesize.$(OBJEXT): compat/$(am__dirstamp)
compat/getline.$(OBJEXT): compat/$(am__dirstamp)
compat/getopt_long.$(OBJEXT): compat/$(am__dirstamp)
compat/getpeereid.$(OBJEXT): compat/$(am__dirstamp)
compat/getprogname.$(OBJEXT): compat/$(am__dirstamp)
compat/htonll.$(OBJEXT): compat/$(am__dirstamp)
compat/imsg-buffer.$(OBJEXT): compat/$(am__dirstamp)
compat/imsg.$(OBJEXT): compat/$(am__dirstamp)
compat/memmem.$(OBJEXT): compat/$(am__dirstamp)
compat/ntohll.$(OBJEXT): compat/$(am__dirstamp)
compat/reallocarray.$(OBJEXT): compat/$(am__dirstamp)
compat/recallocarray.$(OBJEXT): compat/$(am__dirstamp)
compat/setenv.$(OBJEXT): compat/$(am__dirstamp)
compat/setproctitle.$(OBJEXT): compat/$(am__dirstamp)
compat/strcasestr.$(OBJEXT): compat/$(am__dirstamp)
compat/strlcat.$(OBJEXT): compat/$(am__dirstamp)
compat/strlcpy.$(OBJEXT): compat/$(am__dirstamp)
compat/strndup.$(OBJEXT): compat/$(am__dirstamp)
compat/strnlen.$(OBJEXT): compat/$(am__dirstamp)
compat/strsep.$(OBJEXT): compat/$(am__dirstamp)
compat/strtonum.$(OBJEXT): compat/$(am__dirstamp)
compat/unvis.$(OBJEXT): compat/$(am__dirstamp)
compat/vis.$(OBJEXT): compat/$(am__dirstamp)
fuzz/$(am__dirstamp):
	@$(MKDIR_P) fuzz
	@: >>fuzz/$(am__dirstamp)
fuzz/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) fuzz/$(DEPDIR)
	@: >>fuzz/$(DEPDIR)/$(am__dirstamp)
fuzz/cmd-parse-fuzzer.$(OBJEXT): fuzz/$(am__dirstamp) \
	fuzz/$(DEPDIR)/$(am__dirstamp)

fuzz/cmd-parse-fuzzer$(EXEEXT): $(fuzz_cmd_parse_fuzzer_OBJECTS) $(fuzz_cmd_parse_fuzzer_DEPENDENCIES) $(EXTRA_fuzz_cmd_parse_fuzzer_DEPENDENCIES) fuzz/$(am__dirstamp)
	@rm -f fuzz/cmd-parse-fuzzer$(EXEEXT)
	$(AM_V_CCLD)$(fuzz_cmd_parse_fuzzer_LINK) $(fuzz_cmd_parse_fuzzer_OBJECTS) $(fuzz_cmd_parse_fuzzer_LDADD) $(LIBS)
fuzz/format-fuzzer.$(OBJEXT): fuzz/$(am__dirstamp) \
	fuzz/$(DEPDIR)/$(am__dirstamp)

fuzz/format-fuzzer$(EXEEXT): $(fuzz_format_fuzzer_OBJECTS) $(fuzz_format_fuzzer_DEPENDENCIES) $(EXTRA_fuzz_format_fuzzer_DEPENDENCIES) fuzz/$(am__dirstamp)
	@rm -f fuzz/format-fuzzer$(EXEEXT)
	$(AM_V_CCLD)$(fuzz_format_fuzzer_LINK) $(fuzz_format_fuzzer_OBJECTS) $(fuzz_format_fuzzer_LDADD) $(LIBS)
fuzz/input-fuzzer.$(OBJEXT): fuzz/$(am__dirstamp) \
	fuzz/$(DEPDIR)/$(am__dirstamp)

fuzz/input-fuzzer$(EXEEXT): $(fuzz_input_fuzzer_OBJECTS) $(fuzz_input_fuzzer_DEPENDENCIES) $(EXTRA_fuzz_input_fuzzer_DEPENDENCIES) fuzz/$(am__dirstamp)
	@rm -f fuzz/input-fuzzer$(EXEEXT)
	$(AM_V_CCLD)$(fuzz_input_fuzzer_LINK) $(fuzz_input_fuzzer_OBJECTS) $(fuzz_input_fuzzer_LDADD) $(LIBS)
fuzz/style-fuzzer.$(OBJEXT): fuzz/$(am__dirstamp) \
	fuzz/$(DEPDIR)/$(am__dirstamp)

fuzz/style-fuzzer$(EXEEXT): $(fuzz_style_fuzzer_OBJECTS) $(fuzz_style_fuzzer_DEPENDENCIES) $(EXTRA_fuzz_style_fuzzer_DEPENDENCIES) fuzz/$(am__dirstamp)
	@rm -f fuzz/style-fuzzer$(EXEEXT)
	$(AM_V_CCLD)$(fuzz_style_fuzzer_LINK) $(fuzz_style_fuzzer_OBJECTS) $(fuzz_style_fuzzer_LDADD) $(LIBS)
compat/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) compat/$(DEPDIR)
	@: >>compat/$(DEPDIR)/$(am__dirstamp)
compat/forkpty-freebsd.$(OBJEXT): compat/$(am__dirstamp) \
	compat/$(DEPDIR)/$(am__dirstamp)
compat/systemd.$(OBJEXT): compat/$(am__dirstamp) \
	compat/$(DEPDIR)/$(am__dirstamp)
compat/utf8proc.$(OBJEXT): compat/$(am__dirstamp) \
	compat/$(DEPDIR)/$(am__dirstamp)

tmux$(EXEEXT): $(tmux_OBJECTS) $(tmux_DEPENDENCIES) $(EXTRA_tmux_DEPENDENCIES) 
	@rm -f tmux$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(tmux_OBJECTS) $(tmux_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f compat/*.$(OBJEXT)
	-rm -f fuzz/*.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/alerts.Po # am--include-marker
include ./$(DEPDIR)/arguments.Po # am--include-marker
include ./$(DEPDIR)/attributes.Po # am--include-marker
include ./$(DEPDIR)/cfg.Po # am--include-marker
include ./$(DEPDIR)/client.Po # am--include-marker
include ./$(DEPDIR)/cmd-attach-session.Po # am--include-marker
include ./$(DEPDIR)/cmd-bind-key.Po # am--include-marker
include ./$(DEPDIR)/cmd-break-pane.Po # am--include-marker
include ./$(DEPDIR)/cmd-capture-pane.Po # am--include-marker
include ./$(DEPDIR)/cmd-choose-tree.Po # am--include-marker
include ./$(DEPDIR)/cmd-command-prompt.Po # am--include-marker
include ./$(DEPDIR)/cmd-confirm-before.Po # am--include-marker
include ./$(DEPDIR)/cmd-copy-mode.Po # am--include-marker
include ./$(DEPDIR)/cmd-detach-client.Po # am--include-marker
include ./$(DEPDIR)/cmd-display-menu.Po # am--include-marker
include ./$(DEPDIR)/cmd-display-message.Po # am--include-marker
include ./$(DEPDIR)/cmd-display-panes.Po # am--include-marker
include ./$(DEPDIR)/cmd-find-window.Po # am--include-marker
include ./$(DEPDIR)/cmd-find.Po # am--include-marker
include ./$(DEPDIR)/cmd-if-shell.Po # am--include-marker
include ./$(DEPDIR)/cmd-join-pane.Po # am--include-marker
include ./$(DEPDIR)/cmd-kill-pane.Po # am--include-marker
include ./$(DEPDIR)/cmd-kill-server.Po # am--include-marker
include ./$(DEPDIR)/cmd-kill-session.Po # am--include-marker
include ./$(DEPDIR)/cmd-kill-window.Po # am--include-marker
include ./$(DEPDIR)/cmd-list-buffers.Po # am--include-marker
include ./$(DEPDIR)/cmd-list-clients.Po # am--include-marker
include ./$(DEPDIR)/cmd-list-commands.Po # am--include-marker
include ./$(DEPDIR)/cmd-list-keys.Po # am--include-marker
include ./$(DEPDIR)/cmd-list-panes.Po # am--include-marker
include ./$(DEPDIR)/cmd-list-sessions.Po # am--include-marker
include ./$(DEPDIR)/cmd-list-windows.Po # am--include-marker
include ./$(DEPDIR)/cmd-load-buffer.Po # am--include-marker
include ./$(DEPDIR)/cmd-lock-server.Po # am--include-marker
include ./$(DEPDIR)/cmd-move-window.Po # am--include-marker
include ./$(DEPDIR)/cmd-new-session.Po # am--include-marker
include ./$(DEPDIR)/cmd-new-window.Po # am--include-marker
include ./$(DEPDIR)/cmd-parse.Po # am--include-marker
include ./$(DEPDIR)/cmd-paste-buffer.Po # am--include-marker
include ./$(DEPDIR)/cmd-pipe-pane.Po # am--include-marker
include ./$(DEPDIR)/cmd-queue.Po # am--include-marker
include ./$(DEPDIR)/cmd-refresh-client.Po # am--include-marker
include ./$(DEPDIR)/cmd-rename-session.Po # am--include-marker
include ./$(DEPDIR)/cmd-rename-window.Po # am--include-marker
include ./$(DEPDIR)/cmd-resize-pane.Po # am--include-marker
include ./$(DEPDIR)/cmd-resize-window.Po # am--include-marker
include ./$(DEPDIR)/cmd-respawn-pane.Po # am--include-marker
include ./$(DEPDIR)/cmd-respawn-window.Po # am--include-marker
include ./$(DEPDIR)/cmd-rotate-window.Po # am--include-marker
include ./$(DEPDIR)/cmd-run-shell.Po # am--include-marker
include ./$(DEPDIR)/cmd-save-buffer.Po # am--include-marker
include ./$(DEPDIR)/cmd-select-layout.Po # am--include-marker
include ./$(DEPDIR)/cmd-select-pane.Po # am--include-marker
include ./$(DEPDIR)/cmd-select-window.Po # am--include-marker
include ./$(DEPDIR)/cmd-send-keys.Po # am--include-marker
include ./$(DEPDIR)/cmd-server-access.Po # am--include-marker
include ./$(DEPDIR)/cmd-set-buffer.Po # am--include-marker
include ./$(DEPDIR)/cmd-set-environment.Po # am--include-marker
include ./$(DEPDIR)/cmd-set-option.Po # am--include-marker
include ./$(DEPDIR)/cmd-show-environment.Po # am--include-marker
include ./$(DEPDIR)/cmd-show-messages.Po # am--include-marker
include ./$(DEPDIR)/cmd-show-options.Po # am--include-marker
include ./$(DEPDIR)/cmd-show-prompt-history.Po # am--include-marker
include ./$(DEPDIR)/cmd-source-file.Po # am--include-marker
include ./$(DEPDIR)/cmd-split-window.Po # am--include-marker
include ./$(DEPDIR)/cmd-swap-pane.Po # am--include-marker
include ./$(DEPDIR)/cmd-swap-window.Po # am--include-marker
include ./$(DEPDIR)/cmd-switch-client.Po # am--include-marker
include ./$(DEPDIR)/cmd-unbind-key.Po # am--include-marker
include ./$(DEPDIR)/cmd-wait-for.Po # am--include-marker
include ./$(DEPDIR)/cmd.Po # am--include-marker
include ./$(DEPDIR)/colour.Po # am--include-marker
include ./$(DEPDIR)/control-notify.Po # am--include-marker
include ./$(DEPDIR)/control.Po # am--include-marker
include ./$(DEPDIR)/environ.Po # am--include-marker
include ./$(DEPDIR)/file.Po # am--include-marker
include ./$(DEPDIR)/format-draw.Po # am--include-marker
include ./$(DEPDIR)/format.Po # am--include-marker
include ./$(DEPDIR)/grid-reader.Po # am--include-marker
include ./$(DEPDIR)/grid-view.Po # am--include-marker
include ./$(DEPDIR)/grid.Po # am--include-marker
include ./$(DEPDIR)/hyperlinks.Po # am--include-marker
include ./$(DEPDIR)/image-sixel.Po # am--include-marker
include ./$(DEPDIR)/image.Po # am--include-marker
include ./$(DEPDIR)/input-keys.Po # am--include-marker
include ./$(DEPDIR)/input.Po # am--include-marker
include ./$(DEPDIR)/job.Po # am--include-marker
include ./$(DEPDIR)/key-bindings.Po # am--include-marker
include ./$(DEPDIR)/key-string.Po # am--include-marker
include ./$(DEPDIR)/layout-custom.Po # am--include-marker
include ./$(DEPDIR)/layout-set.Po # am--include-marker
include ./$(DEPDIR)/layout.Po # am--include-marker
include ./$(DEPDIR)/log.Po # am--include-marker
include ./$(DEPDIR)/menu.Po # am--include-marker
include ./$(DEPDIR)/mode-tree.Po # am--include-marker
include ./$(DEPDIR)/names.Po # am--include-marker
include ./$(DEPDIR)/notify.Po # am--include-marker
include ./$(DEPDIR)/options-table.Po # am--include-marker
include ./$(DEPDIR)/options.Po # am--include-marker
include ./$(DEPDIR)/osdep-freebsd.Po # am--include-marker
include ./$(DEPDIR)/paste.Po # am--include-marker
include ./$(DEPDIR)/popup.Po # am--include-marker
include ./$(DEPDIR)/proc.Po # am--include-marker
include ./$(DEPDIR)/regsub.Po # am--include-marker
include ./$(DEPDIR)/resize.Po # am--include-marker
include ./$(DEPDIR)/screen-redraw.Po # am--include-marker
include ./$(DEPDIR)/screen-write.Po # am--include-marker
include ./$(DEPDIR)/screen.Po # am--include-marker
include ./$(DEPDIR)/server-acl.Po # am--include-marker
include ./$(DEPDIR)/server-client.Po # am--include-marker
include ./$(DEPDIR)/server-fn.Po # am--include-marker
include ./$(DEPDIR)/server.Po # am--include-marker
include ./$(DEPDIR)/session.Po # am--include-marker
include ./$(DEPDIR)/sort.Po # am--include-marker
include ./$(DEPDIR)/spawn.Po # am--include-marker
include ./$(DEPDIR)/status.Po # am--include-marker
include ./$(DEPDIR)/style.Po # am--include-marker
include ./$(DEPDIR)/tmux.Po # am--include-marker
include ./$(DEPDIR)/tty-acs.Po # am--include-marker
include ./$(DEPDIR)/tty-draw.Po # am--include-marker
include ./$(DEPDIR)/tty-features.Po # am--include-marker
include ./$(DEPDIR)/tty-keys.Po # am--include-marker
include ./$(DEPDIR)/tty-term.Po # am--include-marker
include ./$(DEPDIR)/tty.Po # am--include-marker
include ./$(DEPDIR)/utf8-combined.Po # am--include-marker
include ./$(DEPDIR)/utf8.Po # am--include-marker
include ./$(DEPDIR)/window-border.Po # am--include-marker
include ./$(DEPDIR)/window-buffer.Po # am--include-marker
include ./$(DEPDIR)/window-client.Po # am--include-marker
include ./$(DEPDIR)/window-clock.Po # am--include-marker
include ./$(DEPDIR)/window-copy.Po # am--include-marker
include ./$(DEPDIR)/window-customize.Po # am--include-marker
include ./$(DEPDIR)/window-tree.Po # am--include-marker
include ./$(DEPDIR)/window-visible.Po # am--include-marker
include ./$(DEPDIR)/window.Po # am--include-marker
include ./$(DEPDIR)/xmalloc.Po # am--include-marker
include compat/$(DEPDIR)/asprintf.Po # am--include-marker
include compat/$(DEPDIR)/base64.Po # am--include-marker
include compat/$(DEPDIR)/cfmakeraw.Po # am--include-marker
include compat/$(DEPDIR)/clock_gettime.Po # am--include-marker
include compat/$(DEPDIR)/closefrom.Po # am--include-marker
include compat/$(DEPDIR)/daemon-darwin.Po # am--include-marker
include compat/$(DEPDIR)/daemon.Po # am--include-marker
include compat/$(DEPDIR)/err.Po # am--include-marker
include compat/$(DEPDIR)/explicit_bzero.Po # am--include-marker
include compat/$(DEPDIR)/fdforkpty.Po # am--include-marker
include compat/$(DEPDIR)/fgetln.Po # am--include-marker
include compat/$(DEPDIR)/forkpty-freebsd.Po # am--include-marker
include compat/$(DEPDIR)/freezero.Po # am--include-marker
include compat/$(DEPDIR)/getdtablecount.Po # am--include-marker
include compat/$(DEPDIR)/getdtablesize.Po # am--include-marker
include compat/$(DEPDIR)/getline.Po # am--include-marker
include compat/$(DEPDIR)/getopt_long.Po # am--include-marker
include compat/$(DEPDIR)/getpeereid.Po # am--include-marker
include compat/$(DEPDIR)/getprogname.Po # am--include-marker
include compat/$(DEPDIR)/htonll.Po # am--include-marker
include compat/$(DEPDIR)/imsg-buffer.Po # am--include-marker
include compat/$(DEPDIR)/imsg.Po # am--include-marker
include compat/$(DEPDIR)/memmem.Po # am--include-marker
include compat/$(DEPDIR)/ntohll.Po # am--include-marker
include compat/$(DEPDIR)/reallocarray.Po # am--include-marker
include compat/$(DEPDIR)/recallocarray.Po # am--include-marker
include compat/$(DEPDIR)/setenv.Po # am--include-marker
include compat/$(DEPDIR)/setproctitle.Po # am--include-marker
include compat/$(DEPDIR)/strcasestr.Po # am--include-marker
include compat/$(DEPDIR)/strlcat.Po # am--include-marker
include compat/$(DEPDIR)/strlcpy.Po # am--include-marker
include compat/$(DEPDIR)/strndup.Po # am--include-marker
include compat/$(DEPDIR)/strnlen.Po # am--include-marker
include compat/$(DEPDIR)/strsep.Po # am--include-marker
include compat/$(DEPDIR)/strtonum.Po # am--include-marker
include compat/$(DEPDIR)/systemd.Po # am--include-marker
include compat/$(DEPDIR)/unvis.Po # am--include-marker
include compat/$(DEPDIR)/utf8proc.Po # am--include-marker
include compat/$(DEPDIR)/vis.Po # am--include-marker
include fuzz/$(DEPDIR)/cmd-parse-fuzzer.Po # am--include-marker
include fuzz/$(DEPDIR)/format-fuzzer.Po # am--include-marker
include fuzz/$(DEPDIR)/input-fuzzer.Po # am--include-marker
include fuzz/$(DEPDIR)/style-fuzzer.Po # am--include-marker

$(am__depfiles_remade):
	@$(MKDIR_P) $(@D)
	@: >>$@

am--depfiles: $(am__depfiles_remade)

.c.o:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.y.c:
	$(AM_V_YACC)$(am__skipyacc) $(SHELL) $(YLWRAP) $< y.tab.c $@ y.tab.h `echo $@ | $(am__yacc_c2h)` y.output $*.output -- $(YACCCOMPILE)

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) distdir-am

distdir-am: $(DISTFILES)
	$(am__remove_distdir)
	$(AM_V_at)$(MKDIR_P) "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-bzip3: distdir
	tardir=$(distdir) && $(am__tar) | bzip3 -c >$(distdir).tar.bz3
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-zstd: distdir
	tardir=$(distdir) && $(am__tar) | zstd -c $${ZSTD_CLEVEL-$${ZSTD_OPT--19}} >$(distdir).tar.zst
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  eval GZIP= gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.bz3*) \
	  bzip3 -dc $(distdir).tar.bz3 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  eval GZIP= gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	*.tar.zst*) \
	  zstd -dc $(distdir).tar.zst | $(am__untar) ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) $(AM_DISTCHECK_DVI_TARGET) \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
	$(MAKE) $(AM_MAKEFLAGS) $(check_PROGRAMS)
check: check-am
all-am: Makefile $(PROGRAMS)
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:
	-$(am__rm_f) compat/asprintf.$(OBJEXT)
	-$(am__rm_f) compat/base64.$(OBJEXT)
	-$(am__rm_f) compat/cfmakeraw.$(OBJEXT)
	-$(am__rm_f) compat/clock_gettime.$(OBJEXT)
	-$(am__rm_f) compat/closefrom.$(OBJEXT)
	-$(am__rm_f) compat/daemon-darwin.$(OBJEXT)
	-$(am__rm_f) compat/daemon.$(OBJEXT)
	-$(am__rm_f) compat/err.$(OBJEXT)
	-$(am__rm_f) compat/explicit_bzero.$(OBJEXT)
	-$(am__rm_f) compat/fdforkpty.$(OBJEXT)
	-$(am__rm_f) compat/fgetln.$(OBJEXT)
	-$(am__rm_f) compat/freezero.$(OBJEXT)
	-$(am__rm_f) compat/getdtablecount.$(OBJEXT)
	-$(am__rm_f) compat/getdtablesize.$(OBJEXT)
	-$(am__rm_f) compat/getline.$(OBJEXT)
	-$(am__rm_f) compat/getopt_long.$(OBJEXT)
	-$(am__rm_f) compat/getpeereid.$(OBJEXT)
	-$(am__rm_f) compat/getprogname.$(OBJEXT)
	-$(am__rm_f) compat/htonll.$(OBJEXT)
	-$(am__rm_f) compat/imsg-buffer.$(OBJEXT)
	-$(am__rm_f) compat/imsg.$(OBJEXT)
	-$(am__rm_f) compat/memmem.$(OBJEXT)
	-$(am__rm_f) compat/ntohll.$(OBJEXT)
	-$(am__rm_f) compat/reallocarray.$(OBJEXT)
	-$(am__rm_f) compat/recallocarray.$(OBJEXT)
	-$(am__rm_f) compat/setenv.$(OBJEXT)
	-$(am__rm_f) compat/setproctitle.$(OBJEXT)
	-$(am__rm_f) compat/strcasestr.$(OBJEXT)
	-$(am__rm_f) compat/strlcat.$(OBJEXT)
	-$(am__rm_f) compat/strlcpy.$(OBJEXT)
	-$(am__rm_f) compat/strndup.$(OBJEXT)
	-$(am__rm_f) compat/strnlen.$(OBJEXT)
	-$(am__rm_f) compat/strsep.$(OBJEXT)
	-$(am__rm_f) compat/strtonum.$(OBJEXT)
	-$(am__rm_f) compat/unvis.$(OBJEXT)
	-$(am__rm_f) compat/vis.$(OBJEXT)

clean-generic:
	-$(am__rm_f) $(CLEANFILES)

distclean-generic:
	-$(am__rm_f) $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || $(am__rm_f) $(CONFIG_CLEAN_VPATH_FILES)
	-$(am__rm_f) compat/$(DEPDIR)/$(am__dirstamp)
	-$(am__rm_f) compat/$(am__dirstamp)
	-$(am__rm_f) fuzz/$(DEPDIR)/$(am__dirstamp)
	-$(am__rm_f) fuzz/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
	-$(am__rm_f) cmd-parse.c
clean: clean-am

clean-am: clean-binPROGRAMS clean-checkPROGRAMS clean-generic \
	mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -f ./$(DEPDIR)/alerts.Po
	-rm -f ./$(DEPDIR)/arguments.Po
	-rm -f ./$(DEPDIR)/attributes.Po
	-rm -f ./$(DEPDIR)/cfg.Po
	-rm -f ./$(DEPDIR)/client.Po
	-rm -f ./$(DEPDIR)/cmd-attach-session.Po
	-rm -f ./$(DEPDIR)/cmd-bind-key.Po
	-rm -f ./$(DEPDIR)/cmd-break-pane.Po
	-rm -f ./$(DEPDIR)/cmd-capture-pane.Po
	-rm -f ./$(DEPDIR)/cmd-choose-tree.Po
	-rm -f ./$(DEPDIR)/cmd-command-prompt.Po
	-rm -f ./$(DEPDIR)/cmd-confirm-before.Po
	-rm -f ./$(DEPDIR)/cmd-copy-mode.Po
	-rm -f ./$(DEPDIR)/cmd-detach-client.Po
	-rm -f ./$(DEPDIR)/cmd-display-menu.Po
	-rm -f ./$(DEPDIR)/cmd-display-message.Po
	-rm -f ./$(DEPDIR)/cmd-display-panes.Po
	-rm -f ./$(DEPDIR)/cmd-find-window.Po
	-rm -f ./$(DEPDIR)/cmd-find.Po
	-rm -f ./$(DEPDIR)/cmd-if-shell.Po
	-rm -f ./$(DEPDIR)/cmd-join-pane.Po
	-rm -f ./$(DEPDIR)/cmd-kill-pane.Po
	-rm -f ./$(DEPDIR)/cmd-kill-server.Po
	-rm -f ./$(DEPDIR)/cmd-kill-session.Po
	-rm -f ./$(DEPDIR)/cmd-kill-window.Po
	-rm -f ./$(DEPDIR)/cmd-list-buffers.Po
	-rm -f ./$(DEPDIR)/cmd-list-clients.Po
	-rm -f ./$(DEPDIR)/cmd-list-commands.Po
	-rm -f ./$(DEPDIR)/cmd-list-keys.Po
	-rm -f ./$(DEPDIR)/cmd-list-panes.Po
	-rm -f ./$(DEPDIR)/cmd-list-sessions.Po
	-rm -f ./$(DEPDIR)/cmd-list-windows.Po
	-rm -f ./$(DEPDIR)/cmd-load-buffer.Po
	-rm -f ./$(DEPDIR)/cmd-lock-server.Po
	-rm -f ./$(DEPDIR)/cmd-move-window.Po
	-rm -f ./$(DEPDIR)/cmd-new-session.Po
	-rm -f ./$(DEPDIR)/cmd-new-window.Po
	-rm -f ./$(DEPDIR)/cmd-parse.Po
	-rm -f ./$(DEPDIR)/cmd-paste-buffer.Po
	-rm -f ./$(DEPDIR)/cmd-pipe-pane.Po
	-rm -f ./$(DEPDIR)/cmd-queue.Po
	-rm -f ./$(DEPDIR)/cmd-refresh-client.Po
	-rm -f ./$(DEPDIR)/cmd-rename-session.Po
	-rm -f ./$(DEPDIR)/cmd-rename-window.Po
	-rm -f ./$(DEPDIR)/cmd-resize-pane.Po
	-rm -f ./$(DEPDIR)/cmd-resize-window.Po
	-rm -f ./$(DEPDIR)/cmd-respawn-pane.Po
	-rm -f ./$(DEPDIR)/cmd-respawn-window.Po
	-rm -f ./$(DEPDIR)/cmd-rotate-window.Po
	-rm -f ./$(DEPDIR)/cmd-run-shell.Po
	-rm -f ./$(DEPDIR)/cmd-save-buffer.Po
	-rm -f ./$(DEPDIR)/cmd-select-layout.Po
	-rm -f ./$(DEPDIR)/cmd-select-pane.Po
	-rm -f ./$(DEPDIR)/cmd-select-window.Po
	-rm -f ./$(DEPDIR)/cmd-send-keys.Po
	-rm -f ./$(DEPDIR)/cmd-server-access.Po
	-rm -f ./$(DEPDIR)/cmd-set-buffer.Po
	-rm -f ./$(DEPDIR)/cmd-set-environment.Po
	-rm -f ./$(DEPDIR)/cmd-set-option.Po
	-rm -f ./$(DEPDIR)/cmd-show-environment.Po
	-rm -f ./$(DEPDIR)/cmd-show-messages.Po
	-rm -f ./$(DEPDIR)/cmd-show-options.Po
	-rm -f ./$(DEPDIR)/cmd-show-prompt-history.Po
	-rm -f ./$(DEPDIR)/cmd-source-file.Po
	-rm -f ./$(DEPDIR)/cmd-split-window.Po
	-rm -f ./$(DEPDIR)/cmd-swap-pane.Po
	-rm -f ./$(DEPDIR)/cmd-swap-window.Po
	-rm -f ./$(DEPDIR)/cmd-switch-client.Po
	-rm -f ./$(DEPDIR)/cmd-unbind-key.Po
	-rm -f ./$(DEPDIR)/cmd-wait-for.Po
	-rm -f ./$(DEPDIR)/cmd.Po
	-rm -f ./$(DEPDIR)/colour.Po
	-rm -f ./$(DEPDIR)/control-notify.Po
	-rm -f ./$(DEPDIR)/control.Po
	-rm -f ./$(DEPDIR)/environ.Po
	-rm -f ./$(DEPDIR)/file.Po
	-rm -f ./$(DEPDIR)/format-draw.Po
	-rm -f ./$(DEPDIR)/format.Po
	-rm -f ./$(DEPDIR)/grid-reader.Po
	-rm -f ./$(DEPDIR)/grid-view.Po
	-rm -f ./$(DEPDIR)/grid.Po
	-rm -f ./$(DEPDIR)/hyperlinks.Po
	-rm -f ./$(DEPDIR)/image-sixel.Po
	-rm -f ./$(DEPDIR)/image.Po
	-rm -f ./$(DEPDIR)/input-keys.Po
	-rm -f ./$(DEPDIR)/input.Po
	-rm -f ./$(DEPDIR)/job.Po
	-rm -f ./$(DEPDIR)/key-bindings.Po
	-rm -f ./$(DEPDIR)/key-string.Po
	-rm -f ./$(DEPDIR)/layout-custom.Po
	-rm -f ./$(DEPDIR)/layout-set.Po
	-rm -f ./$(DEPDIR)/layout.Po
	-rm -f ./$(DEPDIR)/log.Po
	-rm -f ./$(DEPDIR)/menu.Po
	-rm -f ./$(DEPDIR)/mode-tree.Po
	-rm -f ./$(DEPDIR)/names.Po
	-rm -f ./$(DEPDIR)/notify.Po
	-rm -f ./$(DEPDIR)/options-table.Po
	-rm -f ./$(DEPDIR)/options.Po
	-rm -f ./$(DEPDIR)/osdep-freebsd.Po
	-rm -f ./$(DEPDIR)/paste.Po
	-rm -f ./$(DEPDIR)/popup.Po
	-rm -f ./$(DEPDIR)/proc.Po
	-rm -f ./$(DEPDIR)/regsub.Po
	-rm -f ./$(DEPDIR)/resize.Po
	-rm -f ./$(DEPDIR)/screen-redraw.Po
	-rm -f ./$(DEPDIR)/screen-write.Po
	-rm -f ./$(DEPDIR)/screen.Po
	-rm -f ./$(DEPDIR)/server-acl.Po
	-rm -f ./$(DEPDIR)/server-client.Po
	-rm -f ./$(DEPDIR)/server-fn.Po
	-rm -f ./$(DEPDIR)/server.Po
	-rm -f ./$(DEPDIR)/session.Po
	-rm -f ./$(DEPDIR)/sort.Po
	-rm -f ./$(DEPDIR)/spawn.Po
	-rm -f ./$(DEPDIR)/status.Po
	-rm -f ./$(DEPDIR)/style.Po
	-rm -f ./$(DEPDIR)/tmux.Po
	-rm -f ./$(DEPDIR)/tty-acs.Po
	-rm -f ./$(DEPDIR)/tty-draw.Po
	-rm -f ./$(DEPDIR)/tty-features.Po
	-rm -f ./$(DEPDIR)/tty-keys.Po
	-rm -f ./$(DEPDIR)/tty-term.Po
	-rm -f ./$(DEPDIR)/tty.Po
	-rm -f ./$(DEPDIR)/utf8-combined.Po
	-rm -f ./$(DEPDIR)/utf8.Po
	-rm -f ./$(DEPDIR)/window-border.Po
	-rm -f ./$(DEPDIR)/window-buffer.Po
	-rm -f ./$(DEPDIR)/window-client.Po
	-rm -f ./$(DEPDIR)/window-clock.Po
	-rm -f ./$(DEPDIR)/window-copy.Po
	-rm -f ./$(DEPDIR)/window-customize.Po
	-rm -f ./$(DEPDIR)/window-tree.Po
	-rm -f ./$(DEPDIR)/window-visible.Po
	-rm -f ./$(DEPDIR)/window.Po
	-rm -f ./$(DEPDIR)/xmalloc.Po
	-rm -f compat/$(DEPDIR)/asprintf.Po
	-rm -f compat/$(DEPDIR)/base64.Po
	-rm -f compat/$(DEPDIR)/cfmakeraw.Po
	-rm -f compat/$(DEPDIR)/clock_gettime.Po
	-rm -f compat/$(DEPDIR)/closefrom.Po
	-rm -f compat/$(DEPDIR)/daemon-darwin.Po
	-rm -f compat/$(DEPDIR)/daemon.Po
	-rm -f compat/$(DEPDIR)/err.Po
	-rm -f compat/$(DEPDIR)/explicit_bzero.Po
	-rm -f compat/$(DEPDIR)/fdforkpty.Po
	-rm -f compat/$(DEPDIR)/fgetln.Po
	-rm -f compat/$(DEPDIR)/forkpty-freebsd.Po
	-rm -f compat/$(DEPDIR)/freezero.Po
	-rm -f compat/$(DEPDIR)/getdtablecount.Po
	-rm -f compat/$(DEPDIR)/getdtablesize.Po
	-rm -f compat/$(DEPDIR)/getline.Po
	-rm -f compat/$(DEPDIR)/getopt_long.Po
	-rm -f compat/$(DEPDIR)/getpeereid.Po
	-rm -f compat/$(DEPDIR)/getprogname.Po
	-rm -f compat/$(DEPDIR)/htonll.Po
	-rm -f compat/$(DEPDIR)/imsg-buffer.Po
	-rm -f compat/$(DEPDIR)/imsg.Po
	-rm -f compat/$(DEPDIR)/memmem.Po
	-rm -f compat/$(DEPDIR)/ntohll.Po
	-rm -f compat/$(DEPDIR)/reallocarray.Po
	-rm -f compat/$(DEPDIR)/recallocarray.Po
	-rm -f compat/$(DEPDIR)/setenv.Po
	-rm -f compat/$(DEPDIR)/setproctitle.Po
	-rm -f compat/$(DEPDIR)/strcasestr.Po
	-rm -f compat/$(DEPDIR)/strlcat.Po
	-rm -f compat/$(DEPDIR)/strlcpy.Po
	-rm -f compat/$(DEPDIR)/strndup.Po
	-rm -f compat/$(DEPDIR)/strnlen.Po
	-rm -f compat/$(DEPDIR)/strsep.Po
	-rm -f compat/$(DEPDIR)/strtonum.Po
	-rm -f compat/$(DEPDIR)/systemd.Po
	-rm -f compat/$(DEPDIR)/unvis.Po
	-rm -f compat/$(DEPDIR)/utf8proc.Po
	-rm -f compat/$(DEPDIR)/vis.Po
	-rm -f fuzz/$(DEPDIR)/cmd-parse-fuzzer.Po
	-rm -f fuzz/$(DEPDIR)/format-fuzzer.Po
	-rm -f fuzz/$(DEPDIR)/input-fuzzer.Po
	-rm -f fuzz/$(DEPDIR)/style-fuzzer.Po
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS
	@$(NORMAL_INSTALL)
	$(MAKE) $(AM_MAKEFLAGS) install-exec-hook
install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -f ./$(DEPDIR)/alerts.Po
	-rm -f ./$(DEPDIR)/arguments.Po
	-rm -f ./$(DEPDIR)/attributes.Po
	-rm -f ./$(DEPDIR)/cfg.Po
	-rm -f ./$(DEPDIR)/client.Po
	-rm -f ./$(DEPDIR)/cmd-attach-session.Po
	-rm -f ./$(DEPDIR)/cmd-bind-key.Po
	-rm -f ./$(DEPDIR)/cmd-break-pane.Po
	-rm -f ./$(DEPDIR)/cmd-capture-pane.Po
	-rm -f ./$(DEPDIR)/cmd-choose-tree.Po
	-rm -f ./$(DEPDIR)/cmd-command-prompt.Po
	-rm -f ./$(DEPDIR)/cmd-confirm-before.Po
	-rm -f ./$(DEPDIR)/cmd-copy-mode.Po
	-rm -f ./$(DEPDIR)/cmd-detach-client.Po
	-rm -f ./$(DEPDIR)/cmd-display-menu.Po
	-rm -f ./$(DEPDIR)/cmd-display-message.Po
	-rm -f ./$(DEPDIR)/cmd-display-panes.Po
	-rm -f ./$(DEPDIR)/cmd-find-window.Po
	-rm -f ./$(DEPDIR)/cmd-find.Po
	-rm -f ./$(DEPDIR)/cmd-if-shell.Po
	-rm -f ./$(DEPDIR)/cmd-join-pane.Po
	-rm -f ./$(DEPDIR)/cmd-kill-pane.Po
	-rm -f ./$(DEPDIR)/cmd-kill-server.Po
	-rm -f ./$(DEPDIR)/cmd-kill-session.Po
	-rm -f ./$(DEPDIR)/cmd-kill-window.Po
	-rm -f ./$(DEPDIR)/cmd-list-buffers.Po
	-rm -f ./$(DEPDIR)/cmd-list-clients.Po
	-rm -f ./$(DEPDIR)/cmd-list-commands.Po
	-rm -f ./$(DEPDIR)/cmd-list-keys.Po
	-rm -f ./$(DEPDIR)/cmd-list-panes.Po
	-rm -f ./$(DEPDIR)/cmd-list-sessions.Po
	-rm -f ./$(DEPDIR)/cmd-list-windows.Po
	-rm -f ./$(DEPDIR)/cmd-load-buffer.Po
	-rm -f ./$(DEPDIR)/cmd-lock-server.Po
	-rm -f ./$(DEPDIR)/cmd-move-window.Po
	-rm -f ./$(DEPDIR)/cmd-new-session.Po
	-rm -f ./$(DEPDIR)/cmd-new-window.Po
	-rm -f ./$(DEPDIR)/cmd-parse.Po
	-rm -f ./$(DEPDIR)/cmd-paste-buffer.Po
	-rm -f ./$(DEPDIR)/cmd-pipe-pane.Po
	-rm -f ./$(DEPDIR)/cmd-queue.Po
	-rm -f ./$(DEPDIR)/cmd-refresh-client.Po
	-rm -f ./$(DEPDIR)/cmd-rename-session.Po
	-rm -f ./$(DEPDIR)/cmd-rename-window.Po
	-rm -f ./$(DEPDIR)/cmd-resize-pane.Po
	-rm -f ./$(DEPDIR)/cmd-resize-window.Po
	-rm -f ./$(DEPDIR)/cmd-respawn-pane.Po
	-rm -f ./$(DEPDIR)/cmd-respawn-window.Po
	-rm -f ./$(DEPDIR)/cmd-rotate-window.Po
	-rm -f ./$(DEPDIR)/cmd-run-shell.Po
	-rm -f ./$(DEPDIR)/cmd-save-buffer.Po
	-rm -f ./$(DEPDIR)/cmd-select-layout.Po
	-rm -f ./$(DEPDIR)/cmd-select-pane.Po
	-rm -f ./$(DEPDIR)/cmd-select-window.Po
	-rm -f ./$(DEPDIR)/cmd-send-keys.Po
	-rm -f ./$(DEPDIR)/cmd-server-access.Po
	-rm -f ./$(DEPDIR)/cmd-set-buffer.Po
	-rm -f ./$(DEPDIR)/cmd-set-environment.Po
	-rm -f ./$(DEPDIR)/cmd-set-option.Po
	-rm -f ./$(DEPDIR)/cmd-show-environment.Po
	-rm -f ./$(DEPDIR)/cmd-show-messages.Po
	-rm -f ./$(DEPDIR)/cmd-show-options.Po
	-rm -f ./$(DEPDIR)/cmd-show-prompt-history.Po
	-rm -f ./$(DEPDIR)/cmd-source-file.Po
	-rm -f ./$(DEPDIR)/cmd-split-window.Po
	-rm -f ./$(DEPDIR)/cmd-swap-pane.Po
	-rm -f ./$(DEPDIR)/cmd-swap-window.Po
	-rm -f ./$(DEPDIR)/cmd-switch-client.Po
	-rm -f ./$(DEPDIR)/cmd-unbind-key.Po
	-rm -f ./$(DEPDIR)/cmd-wait-for.Po
	-rm -f ./$(DEPDIR)/cmd.Po
	-rm -f ./$(DEPDIR)/colour.Po
	-rm -f ./$(DEPDIR)/control-notify.Po
	-rm -f ./$(DEPDIR)/control.Po
	-rm -f ./$(DEPDIR)/environ.Po
	-rm -f ./$(DEPDIR)/file.Po
	-rm -f ./$(DEPDIR)/format-draw.Po
	-rm -f ./$(DEPDIR)/format.Po
	-rm -f ./$(DEPDIR)/grid-reader.Po
	-rm -f ./$(DEPDIR)/grid-view.Po
	-rm -f ./$(DEPDIR)/grid.Po
	-rm -f ./$(DEPDIR)/hyperlinks.Po
	-rm -f ./$(DEPDIR)/image-sixel.Po
	-rm -f ./$(DEPDIR)/image.Po
	-rm -f ./$(DEPDIR)/input-keys.Po
	-rm -f ./$(DEPDIR)/input.Po
	-rm -f ./$(DEPDIR)/job.Po
	-rm -f ./$(DEPDIR)/key-bindings.Po
	-rm -f ./$(DEPDIR)/key-string.Po
	-rm -f ./$(DEPDIR)/layout-custom.Po
	-rm -f ./$(DEPDIR)/layout-set.Po
	-rm -f ./$(DEPDIR)/layout.Po
	-rm -f ./$(DEPDIR)/log.Po
	-rm -f ./$(DEPDIR)/menu.Po
	-rm -f ./$(DEPDIR)/mode-tree.Po
	-rm -f ./$(DEPDIR)/names.Po
	-rm -f ./$(DEPDIR)/notify.Po
	-rm -f ./$(DEPDIR)/options-table.Po
	-rm -f ./$(DEPDIR)/options.Po
	-rm -f ./$(DEPDIR)/osdep-freebsd.Po
	-rm -f ./$(DEPDIR)/paste.Po
	-rm -f ./$(DEPDIR)/popup.Po
	-rm -f ./$(DEPDIR)/proc.Po
	-rm -f ./$(DEPDIR)/regsub.Po
	-rm -f ./$(DEPDIR)/resize.Po
	-rm -f ./$(DEPDIR)/screen-redraw.Po
	-rm -f ./$(DEPDIR)/screen-write.Po
	-rm -f ./$(DEPDIR)/screen.Po
	-rm -f ./$(DEPDIR)/server-acl.Po
	-rm -f ./$(DEPDIR)/server-client.Po
	-rm -f ./$(DEPDIR)/server-fn.Po
	-rm -f ./$(DEPDIR)/server.Po
	-rm -f ./$(DEPDIR)/session.Po
	-rm -f ./$(DEPDIR)/sort.Po
	-rm -f ./$(DEPDIR)/spawn.Po
	-rm -f ./$(DEPDIR)/status.Po
	-rm -f ./$(DEPDIR)/style.Po
	-rm -f ./$(DEPDIR)/tmux.Po
	-rm -f ./$(DEPDIR)/tty-acs.Po
	-rm -f ./$(DEPDIR)/tty-draw.Po
	-rm -f ./$(DEPDIR)/tty-features.Po
	-rm -f ./$(DEPDIR)/tty-keys.Po
	-rm -f ./$(DEPDIR)/tty-term.Po
	-rm -f ./$(DEPDIR)/tty.Po
	-rm -f ./$(DEPDIR)/utf8-combined.Po
	-rm -f ./$(DEPDIR)/utf8.Po
	-rm -f ./$(DEPDIR)/window-border.Po
	-rm -f ./$(DEPDIR)/window-buffer.Po
	-rm -f ./$(DEPDIR)/window-client.Po
	-rm -f ./$(DEPDIR)/window-clock.Po
	-rm -f ./$(DEPDIR)/window-copy.Po
	-rm -f ./$(DEPDIR)/window-customize.Po
	-rm -f ./$(DEPDIR)/window-tree.Po
	-rm -f ./$(DEPDIR)/window-visible.Po
	-rm -f ./$(DEPDIR)/window.Po
	-rm -f ./$(DEPDIR)/xmalloc.Po
	-rm -f compat/$(DEPDIR)/asprintf.Po
	-rm -f compat/$(DEPDIR)/base64.Po
	-rm -f compat/$(DEPDIR)/cfmakeraw.Po
	-rm -f compat/$(DEPDIR)/clock_gettime.Po
	-rm -f compat/$(DEPDIR)/closefrom.Po
	-rm -f compat/$(DEPDIR)/daemon-darwin.Po
	-rm -f compat/$(DEPDIR)/daemon.Po
	-rm -f compat/$(DEPDIR)/err.Po
	-rm -f compat/$(DEPDIR)/explicit_bzero.Po
	-rm -f compat/$(DEPDIR)/fdforkpty.Po
	-rm -f compat/$(DEPDIR)/fgetln.Po
	-rm -f compat/$(DEPDIR)/forkpty-freebsd.Po
	-rm -f compat/$(DEPDIR)/freezero.Po
	-rm -f compat/$(DEPDIR)/getdtablecount.Po
	-rm -f compat/$(DEPDIR)/getdtablesize.Po
	-rm -f compat/$(DEPDIR)/getline.Po
	-rm -f compat/$(DEPDIR)/getopt_long.Po
	-rm -f compat/$(DEPDIR)/getpeereid.Po
	-rm -f compat/$(DEPDIR)/getprogname.Po
	-rm -f compat/$(DEPDIR)/htonll.Po
	-rm -f compat/$(DEPDIR)/imsg-buffer.Po
	-rm -f compat/$(DEPDIR)/imsg.Po
	-rm -f compat/$(DEPDIR)/memmem.Po
	-rm -f compat/$(DEPDIR)/ntohll.Po
	-rm -f compat/$(DEPDIR)/reallocarray.Po
	-rm -f compat/$(DEPDIR)/recallocarray.Po
	-rm -f compat/$(DEPDIR)/setenv.Po
	-rm -f compat/$(DEPDIR)/setproctitle.Po
	-rm -f compat/$(DEPDIR)/strcasestr.Po
	-rm -f compat/$(DEPDIR)/strlcat.Po
	-rm -f compat/$(DEPDIR)/strlcpy.Po
	-rm -f compat/$(DEPDIR)/strndup.Po
	-rm -f compat/$(DEPDIR)/strnlen.Po
	-rm -f compat/$(DEPDIR)/strsep.Po
	-rm -f compat/$(DEPDIR)/strtonum.Po
	-rm -f compat/$(DEPDIR)/systemd.Po
	-rm -f compat/$(DEPDIR)/unvis.Po
	-rm -f compat/$(DEPDIR)/utf8proc.Po
	-rm -f compat/$(DEPDIR)/vis.Po
	-rm -f fuzz/$(DEPDIR)/cmd-parse-fuzzer.Po
	-rm -f fuzz/$(DEPDIR)/format-fuzzer.Po
	-rm -f fuzz/$(DEPDIR)/input-fuzzer.Po
	-rm -f fuzz/$(DEPDIR)/style-fuzzer.Po
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS
	@$(NORMAL_INSTALL)
	$(MAKE) $(AM_MAKEFLAGS) uninstall-hook
.MAKE: check-am install-am install-exec-am install-strip uninstall-am

.PHONY: CTAGS GTAGS TAGS all all-am am--depfiles am--refresh check \
	check-am clean clean-binPROGRAMS clean-checkPROGRAMS \
	clean-cscope clean-generic cscope cscopelist-am ctags ctags-am \
	dist dist-all dist-bzip2 dist-bzip3 dist-gzip dist-lzip \
	dist-shar dist-tarZ dist-xz dist-zip dist-zstd distcheck \
	distclean distclean-compile distclean-generic distclean-tags \
	distcleancheck distdir distuninstallcheck dvi dvi-am html \
	html-am info info-am install install-am install-binPROGRAMS \
	install-data install-data-am install-dvi install-dvi-am \
	install-exec install-exec-am install-exec-hook install-html \
	install-html-am install-info install-info-am install-man \
	install-pdf install-pdf-am install-ps install-ps-am \
	install-strip installcheck installcheck-am installdirs \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic pdf pdf-am ps ps-am \
	tags tags-am uninstall uninstall-am uninstall-binPROGRAMS \
	uninstall-hook

.PRECIOUS: Makefile


# Install tmux.1 in the right format.
install-exec-hook:
	if test xmdoc = xmdoc; then \
		sed -e "s|@SYSCONFDIR@|$(sysconfdir)|g" $(srcdir)/tmux.1 \
			>$(srcdir)/tmux.1.mdoc; \
	else \
		sed -e "s|@SYSCONFDIR@|$(sysconfdir)|g" $(srcdir)/tmux.1| \
			$(AWK) -f $(srcdir)/mdoc2man.awk >$(srcdir)/tmux.1.man; \
	fi
	$(mkdir_p) $(DESTDIR)$(mandir)/man1
	$(INSTALL_DATA) $(srcdir)/tmux.1.mdoc \
		$(DESTDIR)$(mandir)/man1/tmux.1

# And uninstall it.
uninstall-hook:
	rm -f $(DESTDIR)$(mandir)/man1/tmux.1

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:

# Tell GNU make to disable its built-in pattern rules.
%:: %,v
%:: RCS/%,v
%:: RCS/%
%:: s.%
%:: SCCS/s.%
