# Makefile.in generated by automake 1.15.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2017 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# Makefile.am


am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/tmux
pkgincludedir = $(includedir)/tmux
pkglibdir = $(libdir)/tmux
pkglibexecdir = $(libexecdir)/tmux
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-pc-linux-gnu
host_triplet = x86_64-pc-linux-gnu
bin_PROGRAMS = tmux$(EXEEXT)

# Set flags for gcc.
am__append_1 = -std=gnu99 -O2
am__append_2 = -g -Wno-long-long -Wall -W \
	-Wformat=2 -Wmissing-prototypes \
	-Wstrict-prototypes \
	-Wmissing-declarations \
	-Wwrite-strings -Wshadow \
	-Wpointer-arith -Wsign-compare \
	-Wundef -Wbad-function-cast \
	-Winline -Wcast-align \
	-Wdeclaration-after-statement \
	-Wno-pointer-sign -Wno-attributes \
	-Wno-unused-result -Wno-format-y2k
am__append_3 = -DDEBUG
am__append_4 = -iquote.

# Set flags for Solaris.
#am__append_5 = -D_XPG6
##am__append_6 = -D_XPG4_2

# Set flags for Sun CC.
#am__append_7 = -erroff=E_EMPTY_DECLARATION

# Set _LINUX_SOURCE_COMPAT for AIX for malloc(0).
#am__append_8 = -D_LINUX_SOURCE_COMPAT=1

# Set flags for NetBSD.
#am__append_9 = -D_OPENBSD_SOURCE

# Set flags for Haiku.
#am__append_10 = -D_BSD_SOURCE

# Add compat file for forkpty.
#am__append_11 = compat/forkpty-linux.c

# Add compat file for utf8proc.
#am__append_12 = compat/utf8proc.c
#check_PROGRAMS = fuzz/input-fuzzer$(EXEEXT)
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
LIBOBJDIR = compat/
fuzz_input_fuzzer_SOURCES = fuzz/input-fuzzer.c
am__dirstamp = $(am__leading_dot)dirstamp
fuzz_input_fuzzer_OBJECTS = fuzz/input-fuzzer.$(OBJEXT)
#fuzz_input_fuzzer_DEPENDENCIES = $(LDADD)
fuzz_input_fuzzer_LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(fuzz_input_fuzzer_LDFLAGS) $(LDFLAGS) -o $@
dist_tmux_OBJECTS = alerts.$(OBJEXT) arguments.$(OBJEXT) \
	attributes.$(OBJEXT) cfg.$(OBJEXT) client.$(OBJEXT) \
	cmd-attach-session.$(OBJEXT) cmd-bind-key.$(OBJEXT) \
	cmd-break-pane.$(OBJEXT) cmd-capture-pane.$(OBJEXT) \
	cmd-choose-tree.$(OBJEXT) cmd-command-prompt.$(OBJEXT) \
	cmd-confirm-before.$(OBJEXT) cmd-copy-mode.$(OBJEXT) \
	cmd-detach-client.$(OBJEXT) cmd-display-menu.$(OBJEXT) \
	cmd-display-message.$(OBJEXT) cmd-display-panes.$(OBJEXT) \
	cmd-find-window.$(OBJEXT) cmd-find.$(OBJEXT) \
	cmd-if-shell.$(OBJEXT) cmd-join-pane.$(OBJEXT) \
	cmd-kill-pane.$(OBJEXT) cmd-kill-server.$(OBJEXT) \
	cmd-kill-session.$(OBJEXT) cmd-kill-window.$(OBJEXT) \
	cmd-list-buffers.$(OBJEXT) cmd-list-clients.$(OBJEXT) \
	cmd-list-keys.$(OBJEXT) cmd-list-panes.$(OBJEXT) \
	cmd-list-sessions.$(OBJEXT) cmd-list-windows.$(OBJEXT) \
	cmd-load-buffer.$(OBJEXT) cmd-lock-server.$(OBJEXT) \
	cmd-move-window.$(OBJEXT) cmd-new-session.$(OBJEXT) \
	cmd-new-window.$(OBJEXT) cmd-parse.$(OBJEXT) \
	cmd-paste-buffer.$(OBJEXT) cmd-pipe-pane.$(OBJEXT) \
	cmd-queue.$(OBJEXT) cmd-refresh-client.$(OBJEXT) \
	cmd-rename-session.$(OBJEXT) cmd-rename-window.$(OBJEXT) \
	cmd-resize-pane.$(OBJEXT) cmd-resize-window.$(OBJEXT) \
	cmd-respawn-pane.$(OBJEXT) cmd-respawn-window.$(OBJEXT) \
	cmd-rotate-window.$(OBJEXT) cmd-run-shell.$(OBJEXT) \
	cmd-save-buffer.$(OBJEXT) cmd-select-layout.$(OBJEXT) \
	cmd-set-socket.$(OBJEXT) \
	cmd-select-pane.$(OBJEXT) cmd-select-window.$(OBJEXT) \
	cmd-send-keys.$(OBJEXT) cmd-set-buffer.$(OBJEXT) \
	cmd-set-environment.$(OBJEXT) cmd-set-option.$(OBJEXT) \
	cmd-show-environment.$(OBJEXT) cmd-show-messages.$(OBJEXT) \
	cmd-show-options.$(OBJEXT) cmd-source-file.$(OBJEXT) \
	cmd-split-window.$(OBJEXT) cmd-swap-pane.$(OBJEXT) \
	cmd-swap-window.$(OBJEXT) cmd-switch-client.$(OBJEXT) \
	cmd-unbind-key.$(OBJEXT) cmd-wait-for.$(OBJEXT) cmd.$(OBJEXT) \
	colour.$(OBJEXT) control-notify.$(OBJEXT) control.$(OBJEXT) \
	environ.$(OBJEXT) file.$(OBJEXT) format.$(OBJEXT) \
	format-draw.$(OBJEXT) grid-reader.$(OBJEXT) \
	grid-view.$(OBJEXT) grid.$(OBJEXT) input-keys.$(OBJEXT) \
	input.$(OBJEXT) job.$(OBJEXT) key-bindings.$(OBJEXT) \
	key-string.$(OBJEXT) layout-custom.$(OBJEXT) \
	layout-set.$(OBJEXT) layout.$(OBJEXT) log.$(OBJEXT) \
	menu.$(OBJEXT) mode-tree.$(OBJEXT) names.$(OBJEXT) \
	notify.$(OBJEXT) options-table.$(OBJEXT) options.$(OBJEXT) \
	paste.$(OBJEXT) popup.$(OBJEXT) proc.$(OBJEXT) \
	regsub.$(OBJEXT) resize.$(OBJEXT) screen-redraw.$(OBJEXT) \
	screen-write.$(OBJEXT) screen.$(OBJEXT) \
	server-client.$(OBJEXT) server-fn.$(OBJEXT) server.$(OBJEXT) \
	session.$(OBJEXT) spawn.$(OBJEXT) status.$(OBJEXT) \
	style.$(OBJEXT) tmux.$(OBJEXT) tty-acs.$(OBJEXT) \
	tty-features.$(OBJEXT) tty-keys.$(OBJEXT) tty-term.$(OBJEXT) \
	tty.$(OBJEXT) utf8.$(OBJEXT) window-buffer.$(OBJEXT) \
	window-client.$(OBJEXT) window-clock.$(OBJEXT) \
	window-copy.$(OBJEXT) window-customize.$(OBJEXT) \
	window-tree.$(OBJEXT) window.$(OBJEXT) xmalloc.$(OBJEXT)
#am__objects_1 =  \
#	compat/forkpty-linux.$(OBJEXT)
#am__objects_2 = compat/utf8proc.$(OBJEXT)
nodist_tmux_OBJECTS = osdep-linux.$(OBJEXT) $(am__objects_1) \
	$(am__objects_2)
tmux_OBJECTS = $(dist_tmux_OBJECTS) $(nodist_tmux_OBJECTS)
tmux_LDADD = $(LDADD)
tmux_DEPENDENCIES = $(LIBOBJS)
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/etc/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
am__yacc_c2h = sed -e s/cc$$/hh/ -e s/cpp$$/hpp/ -e s/cxx$$/hxx/ \
		   -e s/c++$$/h++/ -e s/c$$/h/
YACCCOMPILE = $(YACC) $(AM_YFLAGS) $(YFLAGS)
AM_V_YACC = $(am__v_YACC_$(V))
am__v_YACC_ = $(am__v_YACC_$(AM_DEFAULT_VERBOSITY))
am__v_YACC_0 = @echo "  YACC    " $@;
am__v_YACC_1 = 
YLWRAP = $(top_srcdir)/etc/ylwrap
SOURCES = fuzz/input-fuzzer.c $(dist_tmux_SOURCES) \
	$(nodist_tmux_SOURCES) $(dist_EXTRA_tmux_SOURCES)
DIST_SOURCES = fuzz/input-fuzzer.c $(dist_tmux_SOURCES) \
	$(dist_EXTRA_tmux_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP)
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
AM_RECURSIVE_TARGETS = cscope
am__DIST_COMMON = $(srcdir)/Makefile.in \
	$(top_srcdir)/compat/asprintf.c $(top_srcdir)/compat/base64.c \
	$(top_srcdir)/compat/cfmakeraw.c \
	$(top_srcdir)/compat/clock_gettime.c \
	$(top_srcdir)/compat/closefrom.c \
	$(top_srcdir)/compat/daemon-darwin.c \
	$(top_srcdir)/compat/daemon.c $(top_srcdir)/compat/err.c \
	$(top_srcdir)/compat/explicit_bzero.c \
	$(top_srcdir)/compat/fdforkpty.c $(top_srcdir)/compat/fgetln.c \
	$(top_srcdir)/compat/freezero.c \
	$(top_srcdir)/compat/getdtablecount.c \
	$(top_srcdir)/compat/getdtablesize.c \
	$(top_srcdir)/compat/getline.c $(top_srcdir)/compat/getopt.c \
	$(top_srcdir)/compat/getprogname.c \
	$(top_srcdir)/compat/imsg-buffer.c $(top_srcdir)/compat/imsg.c \
	$(top_srcdir)/compat/memmem.c \
	$(top_srcdir)/compat/reallocarray.c \
	$(top_srcdir)/compat/recallocarray.c \
	$(top_srcdir)/compat/setenv.c \
	$(top_srcdir)/compat/setproctitle.c \
	$(top_srcdir)/compat/strcasestr.c \
	$(top_srcdir)/compat/strlcat.c $(top_srcdir)/compat/strlcpy.c \
	$(top_srcdir)/compat/strndup.c $(top_srcdir)/compat/strnlen.c \
	$(top_srcdir)/compat/strsep.c $(top_srcdir)/compat/strtonum.c \
	$(top_srcdir)/compat/unvis.c $(top_srcdir)/compat/vis.c \
	$(top_srcdir)/etc/compile $(top_srcdir)/etc/config.guess \
	$(top_srcdir)/etc/config.sub $(top_srcdir)/etc/depcomp \
	$(top_srcdir)/etc/install-sh $(top_srcdir)/etc/missing \
	$(top_srcdir)/etc/ylwrap COPYING README cmd-parse.c \
	etc/compile etc/config.guess etc/config.sub etc/depcomp \
	etc/install-sh etc/missing etc/ylwrap
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/lyonsd3/tmux-source/etc/missing aclocal-1.15
AMTAR = $${TAR-tar}
AM_CFLAGS =  $(am__append_1) $(am__append_2) \
	$(am__append_7)

# Preprocessor flags.
AM_CPPFLAGS = -D_GNU_SOURCE -D_DEFAULT_SOURCE    \
	-DTMUX_VERSION='"next-3.3"' \
	-DTMUX_CONF='"$(sysconfdir)/tmux.conf:~/.tmux.conf:$$XDG_CONFIG_HOME/tmux/tmux.conf:~/.config/tmux/tmux.conf"' \
	-DTMUX_SESSION_EXTRAS $(am__append_3) $(am__append_4) \
	$(am__append_5) $(am__append_6) $(am__append_8) \
	$(am__append_9) $(am__append_10)
AM_DEFAULT_VERBOSITY = 1
AM_LDFLAGS = 
AUTOCONF = ${SHELL} /home/lyonsd3/tmux-source/etc/missing autoconf
AUTOHEADER = ${SHELL} /home/lyonsd3/tmux-source/etc/missing autoheader
AUTOMAKE = ${SHELL} /home/lyonsd3/tmux-source/etc/missing automake-1.15
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = 
CPP = gcc -E
CPPFLAGS = 
CYGPATH_W = echo
DEFS = -DPACKAGE_NAME=\"tmux\" -DPACKAGE_TARNAME=\"tmux\" -DPACKAGE_VERSION=\"next-3.3\" -DPACKAGE_STRING=\"tmux\ next-3.3\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tmux\" -DVERSION=\"next-3.3\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DHAVE_DIRENT_H=1 -DHAVE_FCNTL_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_PATHS_H=1 -DHAVE_PTY_H=1 -DHAVE_STDINT_H=1 -DHAVE_SYS_DIR_H=1 -DHAVE_LIBM=1 -DHAVE_DIRFD=1 -DHAVE_FLOCK=1 -DHAVE_PRCTL=1 -DHAVE_SYSCONF=1 -DHAVE_ASPRINTF=1 -DHAVE_CFMAKERAW=1 -DHAVE_CLOCK_GETTIME=1 -DHAVE_EXPLICIT_BZERO=1 -DHAVE_GETDTABLESIZE=1 -DHAVE_GETLINE=1 -DHAVE_MEMMEM=1 -DHAVE_SETENV=1 -DHAVE_STRCASESTR=1 -DHAVE_STRNDUP=1 -DHAVE_STRSEP=1 -DHAVE_EVENT2_EVENT_H=1 -DHAVE_NCURSES_H=1 -DHAVE_B64_NTOP=1 -DHAVE_MALLOC_TRIM=1 -DHAVE_DAEMON=1 -DHAVE_FORKPTY=1 -DHAVE___PROGNAME=1 -DHAVE_PROGRAM_INVOCATION_SHORT_NAME=1 -DHAVE_PR_SET_NAME=1 -DHAVE_PROC_PID=1
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
FUZZING_LIBS = 
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBEVENT_CFLAGS = 
LIBEVENT_CORE_CFLAGS = 
LIBEVENT_CORE_LIBS = -levent_core
LIBEVENT_LIBS = 
LIBNCURSESW_CFLAGS = 
LIBNCURSESW_LIBS = 
LIBNCURSES_CFLAGS = 
LIBNCURSES_LIBS = 
LIBOBJS =  ${LIBOBJDIR}closefrom$U.o ${LIBOBJDIR}fgetln$U.o ${LIBOBJDIR}freezero$U.o ${LIBOBJDIR}getdtablecount$U.o ${LIBOBJDIR}getprogname$U.o ${LIBOBJDIR}setproctitle$U.o ${LIBOBJDIR}strlcat$U.o ${LIBOBJDIR}strlcpy$U.o ${LIBOBJDIR}strtonum$U.o ${LIBOBJDIR}recallocarray$U.o ${LIBOBJDIR}getopt$U.o ${LIBOBJDIR}imsg$U.o ${LIBOBJDIR}imsg-buffer$U.o ${LIBOBJDIR}vis$U.o ${LIBOBJDIR}unvis$U.o ${LIBOBJDIR}fdforkpty$U.o
LIBS = -lutil -ltinfo -levent_core -lm  -lresolv
LIBTINFO_CFLAGS = -D_GNU_SOURCE -D_DEFAULT_SOURCE
LIBTINFO_LIBS = -ltinfo
LTLIBOBJS =  ${LIBOBJDIR}closefrom$U.lo ${LIBOBJDIR}fgetln$U.lo ${LIBOBJDIR}freezero$U.lo ${LIBOBJDIR}getdtablecount$U.lo ${LIBOBJDIR}getprogname$U.lo ${LIBOBJDIR}setproctitle$U.lo ${LIBOBJDIR}strlcat$U.lo ${LIBOBJDIR}strlcpy$U.lo ${LIBOBJDIR}strtonum$U.lo ${LIBOBJDIR}recallocarray$U.lo ${LIBOBJDIR}getopt$U.lo ${LIBOBJDIR}imsg$U.lo ${LIBOBJDIR}imsg-buffer$U.lo ${LIBOBJDIR}vis$U.lo ${LIBOBJDIR}unvis$U.lo ${LIBOBJDIR}fdforkpty$U.lo
MAKEINFO = ${SHELL} /home/lyonsd3/tmux-source/etc/missing makeinfo
MANFORMAT = mdoc
MKDIR_P = /bin/mkdir -p
OBJEXT = o
PACKAGE = tmux
PACKAGE_BUGREPORT = 
PACKAGE_NAME = tmux
PACKAGE_STRING = tmux next-3.3
PACKAGE_TARNAME = tmux
PACKAGE_URL = 
PACKAGE_VERSION = next-3.3
PATH_SEPARATOR = :
PKG_CONFIG = /usr/bin/pkg-config
PKG_CONFIG_LIBDIR = 
PKG_CONFIG_PATH = 
PLATFORM = linux
SET_MAKE = 
SHELL = /bin/bash
STRIP = 
VERSION = next-3.3
XOPEN_DEFINES = 
YACC = bison -y
YFLAGS = 
abs_builddir = /home/lyonsd3/tmux-source
abs_srcdir = /home/lyonsd3/tmux-source
abs_top_builddir = /home/lyonsd3/tmux-source
abs_top_srcdir = /home/lyonsd3/tmux-source
ac_ct_CC = gcc
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-pc-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = pc
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-pc-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = pc
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/lyonsd3/tmux-source/etc/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
runstatedir = ${localstatedir}/run
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = /etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
CLEANFILES = tmux.1.mdoc tmux.1.man cmd-parse.c

# Distribution tarball options.
EXTRA_DIST = \
	CHANGES README README.ja COPYING example_tmux.conf \
	osdep-*.c mdoc2man.awk tmux.1

dist_EXTRA_tmux_SOURCES = compat/*.[ch]

# Additional object files.
LDADD = $(LIBOBJS)

# List of sources.
dist_tmux_SOURCES = \
	alerts.c \
	arguments.c \
	attributes.c \
	cfg.c \
	client.c \
	cmd-attach-session.c \
	cmd-bind-key.c \
	cmd-break-pane.c \
	cmd-capture-pane.c \
	cmd-choose-tree.c \
	cmd-command-prompt.c \
	cmd-confirm-before.c \
	cmd-copy-mode.c \
	cmd-detach-client.c \
	cmd-display-menu.c \
	cmd-display-message.c \
	cmd-display-panes.c \
	cmd-find-window.c \
	cmd-find.c \
	cmd-if-shell.c \
	cmd-join-pane.c \
	cmd-kill-pane.c \
	cmd-kill-server.c \
	cmd-kill-session.c \
	cmd-kill-window.c \
	cmd-list-buffers.c \
	cmd-list-clients.c \
	cmd-list-keys.c \
	cmd-list-panes.c \
	cmd-list-sessions.c \
	cmd-list-windows.c \
	cmd-load-buffer.c \
	cmd-lock-server.c \
	cmd-move-window.c \
	cmd-new-session.c \
	cmd-new-window.c \
	cmd-parse.y \
	cmd-paste-buffer.c \
	cmd-pipe-pane.c \
	cmd-queue.c \
	cmd-refresh-client.c \
	cmd-rename-session.c \
	cmd-rename-window.c \
	cmd-resize-pane.c \
	cmd-resize-window.c \
	cmd-respawn-pane.c \
	cmd-respawn-window.c \
	cmd-rotate-window.c \
	cmd-run-shell.c \
	cmd-save-buffer.c \
	cmd-select-layout.c \
	cmd-select-pane.c \
	cmd-select-window.c \
	cmd-send-keys.c \
	cmd-set-buffer.c \
	cmd-set-environment.c \
	cmd-set-option.c \
	cmd-show-environment.c \
	cmd-show-messages.c \
	cmd-show-options.c \
	cmd-source-file.c \
	cmd-split-window.c \
	cmd-swap-pane.c \
	cmd-swap-window.c \
	cmd-switch-client.c \
	cmd-unbind-key.c \
	cmd-wait-for.c \
	cmd.c \
	colour.c \
	compat.h \
	control-notify.c \
	control.c \
	environ.c \
	file.c \
	format.c \
	format-draw.c \
	grid-reader.c \
	grid-view.c \
	grid.c \
	input-keys.c \
	input.c \
	job.c \
	key-bindings.c \
	key-string.c \
	layout-custom.c \
	layout-set.c \
	layout.c \
	log.c \
	menu.c \
	mode-tree.c \
	names.c \
	notify.c \
	options-table.c \
	options.c \
	paste.c \
	popup.c \
	proc.c \
	regsub.c \
	resize.c \
	screen-redraw.c \
	screen-write.c \
	screen.c \
	server-client.c \
	server-fn.c \
	server.c \
	session.c \
	spawn.c \
	status.c \
	style.c \
	tmux.c \
	tmux.h \
	tty-acs.c \
	tty-features.c \
	tty-keys.c \
	tty-term.c \
	tty.c \
	utf8.c \
	window-buffer.c \
	window-client.c \
	window-clock.c \
	window-copy.c \
	window-customize.c \
	window-tree.c \
	window.c \
	xmalloc.c \
	xmalloc.h

nodist_tmux_SOURCES = osdep-linux.c $(am__append_11) \
	$(am__append_12)
#fuzz_input_fuzzer_LDFLAGS = $(FUZZING_LIBS)
#fuzz_input_fuzzer_LDADD = $(LDADD) $(tmux_OBJECTS)
all: all-am

.SUFFIXES:
.SUFFIXES: .c .o .obj .y
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)

clean-checkPROGRAMS:
	-test -z "$(check_PROGRAMS)" || rm -f $(check_PROGRAMS)
fuzz/$(am__dirstamp):
	@$(MKDIR_P) fuzz
	@: > fuzz/$(am__dirstamp)
fuzz/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) fuzz/$(DEPDIR)
	@: > fuzz/$(DEPDIR)/$(am__dirstamp)
fuzz/input-fuzzer.$(OBJEXT): fuzz/$(am__dirstamp) \
	fuzz/$(DEPDIR)/$(am__dirstamp)

fuzz/input-fuzzer$(EXEEXT): $(fuzz_input_fuzzer_OBJECTS) $(fuzz_input_fuzzer_DEPENDENCIES) $(EXTRA_fuzz_input_fuzzer_DEPENDENCIES) fuzz/$(am__dirstamp)
	@rm -f fuzz/input-fuzzer$(EXEEXT)
	$(AM_V_CCLD)$(fuzz_input_fuzzer_LINK) $(fuzz_input_fuzzer_OBJECTS) $(fuzz_input_fuzzer_LDADD) $(LIBS)
compat/$(am__dirstamp):
	@$(MKDIR_P) compat
	@: > compat/$(am__dirstamp)
compat/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) compat/$(DEPDIR)
	@: > compat/$(DEPDIR)/$(am__dirstamp)
compat/forkpty-linux.$(OBJEXT): compat/$(am__dirstamp) \
	compat/$(DEPDIR)/$(am__dirstamp)
compat/utf8proc.$(OBJEXT): compat/$(am__dirstamp) \
	compat/$(DEPDIR)/$(am__dirstamp)

tmux$(EXEEXT): $(tmux_OBJECTS) $(tmux_DEPENDENCIES) $(EXTRA_tmux_DEPENDENCIES) 
	@rm -f tmux$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(tmux_OBJECTS) $(tmux_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f compat/*.$(OBJEXT)
	-rm -f fuzz/*.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/alerts.Po
include ./$(DEPDIR)/arguments.Po
include ./$(DEPDIR)/attributes.Po
include ./$(DEPDIR)/cfg.Po
include ./$(DEPDIR)/client.Po
include ./$(DEPDIR)/cmd-attach-session.Po
include ./$(DEPDIR)/cmd-bind-key.Po
include ./$(DEPDIR)/cmd-break-pane.Po
include ./$(DEPDIR)/cmd-capture-pane.Po
include ./$(DEPDIR)/cmd-choose-tree.Po
include ./$(DEPDIR)/cmd-command-prompt.Po
include ./$(DEPDIR)/cmd-confirm-before.Po
include ./$(DEPDIR)/cmd-copy-mode.Po
include ./$(DEPDIR)/cmd-detach-client.Po
include ./$(DEPDIR)/cmd-display-menu.Po
include ./$(DEPDIR)/cmd-display-message.Po
include ./$(DEPDIR)/cmd-display-panes.Po
include ./$(DEPDIR)/cmd-find-window.Po
include ./$(DEPDIR)/cmd-find.Po
include ./$(DEPDIR)/cmd-if-shell.Po
include ./$(DEPDIR)/cmd-join-pane.Po
include ./$(DEPDIR)/cmd-kill-pane.Po
include ./$(DEPDIR)/cmd-kill-server.Po
include ./$(DEPDIR)/cmd-kill-session.Po
include ./$(DEPDIR)/cmd-kill-window.Po
include ./$(DEPDIR)/cmd-list-buffers.Po
include ./$(DEPDIR)/cmd-list-clients.Po
include ./$(DEPDIR)/cmd-list-keys.Po
include ./$(DEPDIR)/cmd-list-panes.Po
include ./$(DEPDIR)/cmd-list-sessions.Po
include ./$(DEPDIR)/cmd-list-windows.Po
include ./$(DEPDIR)/cmd-load-buffer.Po
include ./$(DEPDIR)/cmd-lock-server.Po
include ./$(DEPDIR)/cmd-move-window.Po
include ./$(DEPDIR)/cmd-new-session.Po
include ./$(DEPDIR)/cmd-new-window.Po
include ./$(DEPDIR)/cmd-parse.Po
include ./$(DEPDIR)/cmd-paste-buffer.Po
include ./$(DEPDIR)/cmd-pipe-pane.Po
include ./$(DEPDIR)/cmd-queue.Po
include ./$(DEPDIR)/cmd-refresh-client.Po
include ./$(DEPDIR)/cmd-rename-session.Po
include ./$(DEPDIR)/cmd-rename-window.Po
include ./$(DEPDIR)/cmd-resize-pane.Po
include ./$(DEPDIR)/cmd-resize-window.Po
include ./$(DEPDIR)/cmd-respawn-pane.Po
include ./$(DEPDIR)/cmd-respawn-window.Po
include ./$(DEPDIR)/cmd-rotate-window.Po
include ./$(DEPDIR)/cmd-run-shell.Po
include ./$(DEPDIR)/cmd-save-buffer.Po
include ./$(DEPDIR)/cmd-select-layout.Po
include ./$(DEPDIR)/cmd-select-pane.Po
include ./$(DEPDIR)/cmd-select-window.Po
include ./$(DEPDIR)/cmd-send-keys.Po
include ./$(DEPDIR)/cmd-set-buffer.Po
include ./$(DEPDIR)/cmd-set-environment.Po
include ./$(DEPDIR)/cmd-set-option.Po
include ./$(DEPDIR)/cmd-show-environment.Po
include ./$(DEPDIR)/cmd-show-messages.Po
include ./$(DEPDIR)/cmd-show-options.Po
include ./$(DEPDIR)/cmd-source-file.Po
include ./$(DEPDIR)/cmd-split-window.Po
include ./$(DEPDIR)/cmd-swap-pane.Po
include ./$(DEPDIR)/cmd-swap-window.Po
include ./$(DEPDIR)/cmd-switch-client.Po
include ./$(DEPDIR)/cmd-unbind-key.Po
include ./$(DEPDIR)/cmd-wait-for.Po
include ./$(DEPDIR)/cmd.Po
include ./$(DEPDIR)/colour.Po
include ./$(DEPDIR)/control-notify.Po
include ./$(DEPDIR)/control.Po
include ./$(DEPDIR)/environ.Po
include ./$(DEPDIR)/file.Po
include ./$(DEPDIR)/format-draw.Po
include ./$(DEPDIR)/format.Po
include ./$(DEPDIR)/grid-reader.Po
include ./$(DEPDIR)/grid-view.Po
include ./$(DEPDIR)/grid.Po
include ./$(DEPDIR)/input-keys.Po
include ./$(DEPDIR)/input.Po
include ./$(DEPDIR)/job.Po
include ./$(DEPDIR)/key-bindings.Po
include ./$(DEPDIR)/key-string.Po
include ./$(DEPDIR)/layout-custom.Po
include ./$(DEPDIR)/layout-set.Po
include ./$(DEPDIR)/layout.Po
include ./$(DEPDIR)/log.Po
include ./$(DEPDIR)/menu.Po
include ./$(DEPDIR)/mode-tree.Po
include ./$(DEPDIR)/names.Po
include ./$(DEPDIR)/notify.Po
include ./$(DEPDIR)/options-table.Po
include ./$(DEPDIR)/options.Po
include ./$(DEPDIR)/osdep-linux.Po
include ./$(DEPDIR)/paste.Po
include ./$(DEPDIR)/popup.Po
include ./$(DEPDIR)/proc.Po
include ./$(DEPDIR)/regsub.Po
include ./$(DEPDIR)/resize.Po
include ./$(DEPDIR)/screen-redraw.Po
include ./$(DEPDIR)/screen-write.Po
include ./$(DEPDIR)/screen.Po
include ./$(DEPDIR)/server-client.Po
include ./$(DEPDIR)/server-fn.Po
include ./$(DEPDIR)/server.Po
include ./$(DEPDIR)/session.Po
include ./$(DEPDIR)/spawn.Po
include ./$(DEPDIR)/status.Po
include ./$(DEPDIR)/style.Po
include ./$(DEPDIR)/tmux.Po
include ./$(DEPDIR)/tty-acs.Po
include ./$(DEPDIR)/tty-features.Po
include ./$(DEPDIR)/tty-keys.Po
include ./$(DEPDIR)/tty-term.Po
include ./$(DEPDIR)/tty.Po
include ./$(DEPDIR)/utf8.Po
include ./$(DEPDIR)/window-buffer.Po
include ./$(DEPDIR)/window-client.Po
include ./$(DEPDIR)/window-clock.Po
include ./$(DEPDIR)/window-copy.Po
include ./$(DEPDIR)/window-customize.Po
include ./$(DEPDIR)/window-tree.Po
include ./$(DEPDIR)/window.Po
include ./$(DEPDIR)/xmalloc.Po
include compat/$(DEPDIR)/asprintf.Po
include compat/$(DEPDIR)/base64.Po
include compat/$(DEPDIR)/cfmakeraw.Po
include compat/$(DEPDIR)/clock_gettime.Po
include compat/$(DEPDIR)/closefrom.Po
include compat/$(DEPDIR)/daemon-darwin.Po
include compat/$(DEPDIR)/daemon.Po
include compat/$(DEPDIR)/err.Po
include compat/$(DEPDIR)/explicit_bzero.Po
include compat/$(DEPDIR)/fdforkpty.Po
include compat/$(DEPDIR)/fgetln.Po
include compat/$(DEPDIR)/forkpty-linux.Po
include compat/$(DEPDIR)/freezero.Po
include compat/$(DEPDIR)/getdtablecount.Po
include compat/$(DEPDIR)/getdtablesize.Po
include compat/$(DEPDIR)/getline.Po
include compat/$(DEPDIR)/getopt.Po
include compat/$(DEPDIR)/getprogname.Po
include compat/$(DEPDIR)/imsg-buffer.Po
include compat/$(DEPDIR)/imsg.Po
include compat/$(DEPDIR)/memmem.Po
include compat/$(DEPDIR)/reallocarray.Po
include compat/$(DEPDIR)/recallocarray.Po
include compat/$(DEPDIR)/setenv.Po
include compat/$(DEPDIR)/setproctitle.Po
include compat/$(DEPDIR)/strcasestr.Po
include compat/$(DEPDIR)/strlcat.Po
include compat/$(DEPDIR)/strlcpy.Po
include compat/$(DEPDIR)/strndup.Po
include compat/$(DEPDIR)/strnlen.Po
include compat/$(DEPDIR)/strsep.Po
include compat/$(DEPDIR)/strtonum.Po
include compat/$(DEPDIR)/unvis.Po
include compat/$(DEPDIR)/utf8proc.Po
include compat/$(DEPDIR)/vis.Po
include fuzz/$(DEPDIR)/input-fuzzer.Po

.c.o:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.y.c:
	$(AM_V_YACC)$(am__skipyacc) $(SHELL) $(YLWRAP) $< y.tab.c $@ y.tab.h `echo $@ | $(am__yacc_c2h)` y.output $*.output -- $(YACCCOMPILE)

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
	$(MAKE) $(AM_MAKEFLAGS) $(check_PROGRAMS)
check: check-am
all-am: Makefile $(PROGRAMS)
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:
	-test -z "$(LIBOBJS)" || rm -f $(LIBOBJS)

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f compat/$(DEPDIR)/$(am__dirstamp)
	-rm -f compat/$(am__dirstamp)
	-rm -f fuzz/$(DEPDIR)/$(am__dirstamp)
	-rm -f fuzz/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
	-rm -f cmd-parse.c
clean: clean-am

clean-am: clean-binPROGRAMS clean-checkPROGRAMS clean-generic \
	mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR) compat/$(DEPDIR) fuzz/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS
	@$(NORMAL_INSTALL)
	$(MAKE) $(AM_MAKEFLAGS) install-exec-hook
install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR) compat/$(DEPDIR) fuzz/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: check-am install-am install-exec-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-checkPROGRAMS clean-cscope \
	clean-generic cscope cscopelist-am ctags ctags-am dist \
	dist-all dist-bzip2 dist-gzip dist-lzip dist-shar dist-tarZ \
	dist-xz dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-exec-hook install-html install-html-am \
	install-info install-info-am install-man install-pdf \
	install-pdf-am install-ps install-ps-am install-strip \
	installcheck installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags tags-am uninstall \
	uninstall-am uninstall-binPROGRAMS

.PRECIOUS: Makefile


# Install tmux.1 in the right format.
install-exec-hook:
	if test xmdoc = xmdoc; then \
		sed -e "s|@SYSCONFDIR@|$(sysconfdir)|g" $(srcdir)/tmux.1 \
			>$(srcdir)/tmux.1.mdoc; \
	else \
		sed -e "s|@SYSCONFDIR@|$(sysconfdir)|g" $(srcdir)/tmux.1| \
			$(AWK) -f $(srcdir)/mdoc2man.awk >$(srcdir)/tmux.1.man; \
	fi
	$(mkdir_p) $(DESTDIR)$(mandir)/man1
	$(INSTALL_DATA) $(srcdir)/tmux.1.mdoc \
		$(DESTDIR)$(mandir)/man1/tmux.1

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
