.\" $Id: tmux.1,v 1.3 2007-11-09 16:04:29 nicm Exp $
.\"
.\" Copyright (c) 2007 Nicholas Marriott <nicm@users.sourceforge.net>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF MIND, USE, DATA OR PROFITS, WHETHER
.\" IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
.\" OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd November 9, 2007
.Dt TMUX 1
.Os
.Sh NAME
.Nm tmux
.Nd "terminal multiplexer"
.Sh SYNOPSIS
.Nm tmux
.Bk -words
.Op Fl vV
.Op Fl S Ar socket-path
.Op Fl s Ar session-name
.Ar command
.Op Ar arguments
.Ek
.Sh DESCRIPTION
.Nm
is a terminal multiplexer; it enables a number of terminals (or windows) to be
accessed and controlled from a single terminal.
.Pp
.Nm
runs as a server-client system. A server is created automatically when
necessary and holds a number of
.Em sessions ,
each of which may have a number of
.Em windows
connected to it. Any number of clients may connect to a session, or the server
may be controlled by issuing commands with the
.Nm
binary. Communication takes place through a socket, by default placed in
.Pa /tmp .
.Pp
The options are as follows:
.Bl -tag -width "XXXXXXXXXXXX"
.It Fl S Ar socket-path
This specifies an alternative path to the server socket.
The default is
.Pa /tmp/tmux-UID ,
where
.Em UID
is the uid of the user who invoked
.Nm .
.It Fl s Ar session-name
Apply command to the session named
.Ar session-name .
This option does not apply to all commands.
If it is omitted and
.Nm
is invoked from a running
.Nm
client, the session the containing client is connected to will be used;
otherwise, if only one session exists, it is chosen, or if multiple sessions
exist, an error is generated.
.It Fl v
Request verbose logging.
This option may be specified multiple times for increasing verbosity.
Log messages will be saved into
.Pa tmux-client-PID.log
and
.Pa tmux-server-PID.log
files in the current directory, where
.Em PID
is the pid of the server or client process.
.It Ar command Op Ar arguments
This specifies one of a set of commands used to control
.Nm ,
and described in the following section.
.Pp
.El
.Sh COMMANDS
.Nm
supports the following commands:
.Bl -tag -width Ds
.It Xo Ic attach-session
.Op Fl d
.Xc
.D1 (Alias: Ic attach )
.It Xo Ic bind-key
.Ar key Ar command Op Ar arguments
.Xc
.D1 (Alias: Ic bind )
.It Xo Ic detach-session
.Op Fl a
.Xc
.D1 (Alias: Ic detach )
.It Xo Ic has-session 
.Xc
.D1 (Alias: Ic has )
.It Xo Ic kill-window 
.Op Fl i Ar index
.Xc
.D1 (Alias: Ic killw )
.It Xo Ic last-window 
.Xc
.D1 (Alias: Ic last )
.It Xo Ic link-window 
.Op Fl i Ar index
.Ar name Ar index
.Xc
.D1 (Alias: Ic linkw )
.It Xo Ic list-clients 
.Xc
.D1 (Alias: Ic lsc )
.It Xo Ic list-keys 
.Xc
.D1 (Alias: Ic lsk )
.It Xo Ic list-sessions 
.Xc
.D1 (Alias: Ic ls )
.It Xo Ic list-windows
.Xc
.D1 (Alias: Ic lsw )
.It Xo Ic new-session
.Op Fl d
.Op Fl s Ar session-name
.Op Fl n Ar window-name
.Op Ar command
.Xc
.D1 (Alias: Ic new )
.It Xo Ic new-window 
.Op Fl d
.Op Fl i Ar index
.Op Fl n Ar name
.Op Ar command
.Xc
.D1 (Alias: Ic neww )
.It Xo Ic next-window 
.Xc
.D1 (Alias: Ic next )
.It Xo Ic previous-window 
.Xc
.D1 (Alias: Ic prev )
.It Xo Ic refresh-session 
.Op Fl a
.Xc
.D1 (Alias: Ic refresh )
.It Xo Ic rename-session new-name
.Xc
.D1 (Alias: Ic rename )
.It Xo Ic rename-window
.Op Fl i Ar index
.Ar new-name
.Xc
.D1 (Alias: Ic renamew )
.It Xo Ic select-window 
.Ar index
.Xc
.D1 (Alias: Ic selectw )
.It Xo Ic send-prefix
.Xc
.It Xo Ic set-option  )
.Ar option Ar value
.Xc
.D1 (Alias: Ic set )
.It Xo Ic swap-window 
.Op Fl i Ar index
.Ar name Ar index
.Xc
.D1 (Alias: Ic swapw )
.It Xo Ic unbind-key
.Ar key
.Xc
.D1 (Alias: Ic unbind )
.It Xo Ic unlink-window 
.Op Fl i Ar index
.Xc
.D1 (Alias: Ic unlinkw )
.El
.Sh SEE ALSO
.Xr pty 4
.Sh AUTHORS
.An Nicholas Marriott Aq nicm@users.sourceforge.net
